with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: mocks
filename: "{{.MockName}}.go"
disable-version-string: true
resolve-type-alias: false
issue-845-fix: true
packages:
  rocha/tmux:
    interfaces:
      SessionManager:
      Attacher:
      PaneOperations:
      Configurator:
      Client:
