dir: '{{.InterfaceDir}}/mocks'
structname: Mock{{.InterfaceName}}
pkgname: mocks
filename: "mock_{{.InterfaceName | snakecase }}.go"
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/renato0307/rocha/internal/ports:
    interfaces:
      GitRepository: {}
      ProcessInspector: {}
      SessionReader: {}
      SessionRepository: {}
      SessionStateUpdater: {}
      SessionWriter: {}
      SoundPlayer: {}
      TmuxClient: {}
      TmuxSessionLifecycle: {}
      TokenUsageReader: {}
  github.com/renato0307/rocha/internal/services:
    interfaces:
      ClaudeDirResolver: {}
