// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	tmux "rocha/tmux"

	mock "github.com/stretchr/testify/mock"
)

// MockSessionManager is an autogenerated mock type for the SessionManager type
type MockSessionManager struct {
	mock.Mock
}

type MockSessionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionManager) EXPECT() *MockSessionManager_Expecter {
	return &MockSessionManager_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: name, worktreePath
func (_m *MockSessionManager) Create(name string, worktreePath string) (*tmux.Session, error) {
	ret := _m.Called(name, worktreePath)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *tmux.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*tmux.Session, error)); ok {
		return rf(name, worktreePath)
	}
	if rf, ok := ret.Get(0).(func(string, string) *tmux.Session); ok {
		r0 = rf(name, worktreePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tmux.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, worktreePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
//   - worktreePath string
func (_e *MockSessionManager_Expecter) Create(name interface{}, worktreePath interface{}) *MockSessionManager_Create_Call {
	return &MockSessionManager_Create_Call{Call: _e.mock.On("Create", name, worktreePath)}
}

func (_c *MockSessionManager_Create_Call) Run(run func(name string, worktreePath string)) *MockSessionManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockSessionManager_Create_Call) Return(_a0 *tmux.Session, _a1 error) *MockSessionManager_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionManager_Create_Call) RunAndReturn(run func(string, string) (*tmux.Session, error)) *MockSessionManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: name
func (_m *MockSessionManager) Exists(name string) bool {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockSessionManager_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockSessionManager_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - name string
func (_e *MockSessionManager_Expecter) Exists(name interface{}) *MockSessionManager_Exists_Call {
	return &MockSessionManager_Exists_Call{Call: _e.mock.On("Exists", name)}
}

func (_c *MockSessionManager_Exists_Call) Run(run func(name string)) *MockSessionManager_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionManager_Exists_Call) Return(_a0 bool) *MockSessionManager_Exists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionManager_Exists_Call) RunAndReturn(run func(string) bool) *MockSessionManager_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Kill provides a mock function with given fields: name
func (_m *MockSessionManager) Kill(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionManager_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockSessionManager_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
//   - name string
func (_e *MockSessionManager_Expecter) Kill(name interface{}) *MockSessionManager_Kill_Call {
	return &MockSessionManager_Kill_Call{Call: _e.mock.On("Kill", name)}
}

func (_c *MockSessionManager_Kill_Call) Run(run func(name string)) *MockSessionManager_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionManager_Kill_Call) Return(_a0 error) *MockSessionManager_Kill_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionManager_Kill_Call) RunAndReturn(run func(string) error) *MockSessionManager_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with no fields
func (_m *MockSessionManager) List() ([]*tmux.Session, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*tmux.Session
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*tmux.Session, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*tmux.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tmux.Session)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionManager_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSessionManager_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockSessionManager_Expecter) List() *MockSessionManager_List_Call {
	return &MockSessionManager_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockSessionManager_List_Call) Run(run func()) *MockSessionManager_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionManager_List_Call) Return(_a0 []*tmux.Session, _a1 error) *MockSessionManager_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionManager_List_Call) RunAndReturn(run func() ([]*tmux.Session, error)) *MockSessionManager_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionManager creates a new instance of MockSessionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionManager {
	mock := &MockSessionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
