// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockAttacher is an autogenerated mock type for the Attacher type
type MockAttacher struct {
	mock.Mock
}

type MockAttacher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttacher) EXPECT() *MockAttacher_Expecter {
	return &MockAttacher_Expecter{mock: &_m.Mock}
}

// Attach provides a mock function with given fields: sessionName
func (_m *MockAttacher) Attach(sessionName string) (chan struct{}, error) {
	ret := _m.Called(sessionName)

	if len(ret) == 0 {
		panic("no return value specified for Attach")
	}

	var r0 chan struct{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (chan struct{}, error)); ok {
		return rf(sessionName)
	}
	if rf, ok := ret.Get(0).(func(string) chan struct{}); ok {
		r0 = rf(sessionName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan struct{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sessionName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttacher_Attach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attach'
type MockAttacher_Attach_Call struct {
	*mock.Call
}

// Attach is a helper method to define mock.On call
//   - sessionName string
func (_e *MockAttacher_Expecter) Attach(sessionName interface{}) *MockAttacher_Attach_Call {
	return &MockAttacher_Attach_Call{Call: _e.mock.On("Attach", sessionName)}
}

func (_c *MockAttacher_Attach_Call) Run(run func(sessionName string)) *MockAttacher_Attach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAttacher_Attach_Call) Return(_a0 chan struct{}, _a1 error) *MockAttacher_Attach_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttacher_Attach_Call) RunAndReturn(run func(string) (chan struct{}, error)) *MockAttacher_Attach_Call {
	_c.Call.Return(run)
	return _c
}

// Detach provides a mock function with given fields: sessionName
func (_m *MockAttacher) Detach(sessionName string) error {
	ret := _m.Called(sessionName)

	if len(ret) == 0 {
		panic("no return value specified for Detach")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sessionName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAttacher_Detach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detach'
type MockAttacher_Detach_Call struct {
	*mock.Call
}

// Detach is a helper method to define mock.On call
//   - sessionName string
func (_e *MockAttacher_Expecter) Detach(sessionName interface{}) *MockAttacher_Detach_Call {
	return &MockAttacher_Detach_Call{Call: _e.mock.On("Detach", sessionName)}
}

func (_c *MockAttacher_Detach_Call) Run(run func(sessionName string)) *MockAttacher_Detach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAttacher_Detach_Call) Return(_a0 error) *MockAttacher_Detach_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAttacher_Detach_Call) RunAndReturn(run func(string) error) *MockAttacher_Detach_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAttacher creates a new instance of MockAttacher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttacher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttacher {
	mock := &MockAttacher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
