// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPaneOperations is an autogenerated mock type for the PaneOperations type
type MockPaneOperations struct {
	mock.Mock
}

type MockPaneOperations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaneOperations) EXPECT() *MockPaneOperations_Expecter {
	return &MockPaneOperations_Expecter{mock: &_m.Mock}
}

// CapturePane provides a mock function with given fields: sessionName, startLine
func (_m *MockPaneOperations) CapturePane(sessionName string, startLine int) (string, error) {
	ret := _m.Called(sessionName, startLine)

	if len(ret) == 0 {
		panic("no return value specified for CapturePane")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (string, error)); ok {
		return rf(sessionName, startLine)
	}
	if rf, ok := ret.Get(0).(func(string, int) string); ok {
		r0 = rf(sessionName, startLine)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(sessionName, startLine)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaneOperations_CapturePane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CapturePane'
type MockPaneOperations_CapturePane_Call struct {
	*mock.Call
}

// CapturePane is a helper method to define mock.On call
//   - sessionName string
//   - startLine int
func (_e *MockPaneOperations_Expecter) CapturePane(sessionName interface{}, startLine interface{}) *MockPaneOperations_CapturePane_Call {
	return &MockPaneOperations_CapturePane_Call{Call: _e.mock.On("CapturePane", sessionName, startLine)}
}

func (_c *MockPaneOperations_CapturePane_Call) Run(run func(sessionName string, startLine int)) *MockPaneOperations_CapturePane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockPaneOperations_CapturePane_Call) Return(_a0 string, _a1 error) *MockPaneOperations_CapturePane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaneOperations_CapturePane_Call) RunAndReturn(run func(string, int) (string, error)) *MockPaneOperations_CapturePane_Call {
	_c.Call.Return(run)
	return _c
}

// SendKeys provides a mock function with given fields: sessionName, keys
func (_m *MockPaneOperations) SendKeys(sessionName string, keys ...string) error {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, sessionName)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SendKeys")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...string) error); ok {
		r0 = rf(sessionName, keys...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaneOperations_SendKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendKeys'
type MockPaneOperations_SendKeys_Call struct {
	*mock.Call
}

// SendKeys is a helper method to define mock.On call
//   - sessionName string
//   - keys ...string
func (_e *MockPaneOperations_Expecter) SendKeys(sessionName interface{}, keys ...interface{}) *MockPaneOperations_SendKeys_Call {
	return &MockPaneOperations_SendKeys_Call{Call: _e.mock.On("SendKeys",
		append([]interface{}{sessionName}, keys...)...)}
}

func (_c *MockPaneOperations_SendKeys_Call) Run(run func(sessionName string, keys ...string)) *MockPaneOperations_SendKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockPaneOperations_SendKeys_Call) Return(_a0 error) *MockPaneOperations_SendKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaneOperations_SendKeys_Call) RunAndReturn(run func(string, ...string) error) *MockPaneOperations_SendKeys_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaneOperations creates a new instance of MockPaneOperations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaneOperations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaneOperations {
	mock := &MockPaneOperations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
