// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	tmux "rocha/tmux"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Attach provides a mock function with given fields: sessionName
func (_m *MockClient) Attach(sessionName string) (chan struct{}, error) {
	ret := _m.Called(sessionName)

	if len(ret) == 0 {
		panic("no return value specified for Attach")
	}

	var r0 chan struct{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (chan struct{}, error)); ok {
		return rf(sessionName)
	}
	if rf, ok := ret.Get(0).(func(string) chan struct{}); ok {
		r0 = rf(sessionName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan struct{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sessionName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Attach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attach'
type MockClient_Attach_Call struct {
	*mock.Call
}

// Attach is a helper method to define mock.On call
//   - sessionName string
func (_e *MockClient_Expecter) Attach(sessionName interface{}) *MockClient_Attach_Call {
	return &MockClient_Attach_Call{Call: _e.mock.On("Attach", sessionName)}
}

func (_c *MockClient_Attach_Call) Run(run func(sessionName string)) *MockClient_Attach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_Attach_Call) Return(_a0 chan struct{}, _a1 error) *MockClient_Attach_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Attach_Call) RunAndReturn(run func(string) (chan struct{}, error)) *MockClient_Attach_Call {
	_c.Call.Return(run)
	return _c
}

// BindKey provides a mock function with given fields: table, key, command
func (_m *MockClient) BindKey(table string, key string, command string) error {
	ret := _m.Called(table, key, command)

	if len(ret) == 0 {
		panic("no return value specified for BindKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(table, key, command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_BindKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindKey'
type MockClient_BindKey_Call struct {
	*mock.Call
}

// BindKey is a helper method to define mock.On call
//   - table string
//   - key string
//   - command string
func (_e *MockClient_Expecter) BindKey(table interface{}, key interface{}, command interface{}) *MockClient_BindKey_Call {
	return &MockClient_BindKey_Call{Call: _e.mock.On("BindKey", table, key, command)}
}

func (_c *MockClient_BindKey_Call) Run(run func(table string, key string, command string)) *MockClient_BindKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_BindKey_Call) Return(_a0 error) *MockClient_BindKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_BindKey_Call) RunAndReturn(run func(string, string, string) error) *MockClient_BindKey_Call {
	_c.Call.Return(run)
	return _c
}

// CapturePane provides a mock function with given fields: sessionName, startLine
func (_m *MockClient) CapturePane(sessionName string, startLine int) (string, error) {
	ret := _m.Called(sessionName, startLine)

	if len(ret) == 0 {
		panic("no return value specified for CapturePane")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (string, error)); ok {
		return rf(sessionName, startLine)
	}
	if rf, ok := ret.Get(0).(func(string, int) string); ok {
		r0 = rf(sessionName, startLine)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(sessionName, startLine)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CapturePane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CapturePane'
type MockClient_CapturePane_Call struct {
	*mock.Call
}

// CapturePane is a helper method to define mock.On call
//   - sessionName string
//   - startLine int
func (_e *MockClient_Expecter) CapturePane(sessionName interface{}, startLine interface{}) *MockClient_CapturePane_Call {
	return &MockClient_CapturePane_Call{Call: _e.mock.On("CapturePane", sessionName, startLine)}
}

func (_c *MockClient_CapturePane_Call) Run(run func(sessionName string, startLine int)) *MockClient_CapturePane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockClient_CapturePane_Call) Return(_a0 string, _a1 error) *MockClient_CapturePane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CapturePane_Call) RunAndReturn(run func(string, int) (string, error)) *MockClient_CapturePane_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: name, worktreePath
func (_m *MockClient) Create(name string, worktreePath string) (*tmux.Session, error) {
	ret := _m.Called(name, worktreePath)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *tmux.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*tmux.Session, error)); ok {
		return rf(name, worktreePath)
	}
	if rf, ok := ret.Get(0).(func(string, string) *tmux.Session); ok {
		r0 = rf(name, worktreePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tmux.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, worktreePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
//   - worktreePath string
func (_e *MockClient_Expecter) Create(name interface{}, worktreePath interface{}) *MockClient_Create_Call {
	return &MockClient_Create_Call{Call: _e.mock.On("Create", name, worktreePath)}
}

func (_c *MockClient_Create_Call) Run(run func(name string, worktreePath string)) *MockClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockClient_Create_Call) Return(_a0 *tmux.Session, _a1 error) *MockClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Create_Call) RunAndReturn(run func(string, string) (*tmux.Session, error)) *MockClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Detach provides a mock function with given fields: sessionName
func (_m *MockClient) Detach(sessionName string) error {
	ret := _m.Called(sessionName)

	if len(ret) == 0 {
		panic("no return value specified for Detach")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sessionName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Detach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detach'
type MockClient_Detach_Call struct {
	*mock.Call
}

// Detach is a helper method to define mock.On call
//   - sessionName string
func (_e *MockClient_Expecter) Detach(sessionName interface{}) *MockClient_Detach_Call {
	return &MockClient_Detach_Call{Call: _e.mock.On("Detach", sessionName)}
}

func (_c *MockClient_Detach_Call) Run(run func(sessionName string)) *MockClient_Detach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_Detach_Call) Return(_a0 error) *MockClient_Detach_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Detach_Call) RunAndReturn(run func(string) error) *MockClient_Detach_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: name
func (_m *MockClient) Exists(name string) bool {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockClient_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockClient_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - name string
func (_e *MockClient_Expecter) Exists(name interface{}) *MockClient_Exists_Call {
	return &MockClient_Exists_Call{Call: _e.mock.On("Exists", name)}
}

func (_c *MockClient_Exists_Call) Run(run func(name string)) *MockClient_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_Exists_Call) Return(_a0 bool) *MockClient_Exists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Exists_Call) RunAndReturn(run func(string) bool) *MockClient_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Kill provides a mock function with given fields: name
func (_m *MockClient) Kill(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockClient_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
//   - name string
func (_e *MockClient_Expecter) Kill(name interface{}) *MockClient_Kill_Call {
	return &MockClient_Kill_Call{Call: _e.mock.On("Kill", name)}
}

func (_c *MockClient_Kill_Call) Run(run func(name string)) *MockClient_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_Kill_Call) Return(_a0 error) *MockClient_Kill_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Kill_Call) RunAndReturn(run func(string) error) *MockClient_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with no fields
func (_m *MockClient) List() ([]*tmux.Session, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*tmux.Session
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*tmux.Session, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*tmux.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tmux.Session)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockClient_Expecter) List() *MockClient_List_Call {
	return &MockClient_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockClient_List_Call) Run(run func()) *MockClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_List_Call) Return(_a0 []*tmux.Session, _a1 error) *MockClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_List_Call) RunAndReturn(run func() ([]*tmux.Session, error)) *MockClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// SendKeys provides a mock function with given fields: sessionName, keys
func (_m *MockClient) SendKeys(sessionName string, keys ...string) error {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, sessionName)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SendKeys")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...string) error); ok {
		r0 = rf(sessionName, keys...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_SendKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendKeys'
type MockClient_SendKeys_Call struct {
	*mock.Call
}

// SendKeys is a helper method to define mock.On call
//   - sessionName string
//   - keys ...string
func (_e *MockClient_Expecter) SendKeys(sessionName interface{}, keys ...interface{}) *MockClient_SendKeys_Call {
	return &MockClient_SendKeys_Call{Call: _e.mock.On("SendKeys",
		append([]interface{}{sessionName}, keys...)...)}
}

func (_c *MockClient_SendKeys_Call) Run(run func(sessionName string, keys ...string)) *MockClient_SendKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_SendKeys_Call) Return(_a0 error) *MockClient_SendKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_SendKeys_Call) RunAndReturn(run func(string, ...string) error) *MockClient_SendKeys_Call {
	_c.Call.Return(run)
	return _c
}

// SourceFile provides a mock function with given fields: configPath
func (_m *MockClient) SourceFile(configPath string) error {
	ret := _m.Called(configPath)

	if len(ret) == 0 {
		panic("no return value specified for SourceFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(configPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_SourceFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SourceFile'
type MockClient_SourceFile_Call struct {
	*mock.Call
}

// SourceFile is a helper method to define mock.On call
//   - configPath string
func (_e *MockClient_Expecter) SourceFile(configPath interface{}) *MockClient_SourceFile_Call {
	return &MockClient_SourceFile_Call{Call: _e.mock.On("SourceFile", configPath)}
}

func (_c *MockClient_SourceFile_Call) Run(run func(configPath string)) *MockClient_SourceFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_SourceFile_Call) Return(_a0 error) *MockClient_SourceFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_SourceFile_Call) RunAndReturn(run func(string) error) *MockClient_SourceFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
