// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockConfigurator is an autogenerated mock type for the Configurator type
type MockConfigurator struct {
	mock.Mock
}

type MockConfigurator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigurator) EXPECT() *MockConfigurator_Expecter {
	return &MockConfigurator_Expecter{mock: &_m.Mock}
}

// BindKey provides a mock function with given fields: table, key, command
func (_m *MockConfigurator) BindKey(table string, key string, command string) error {
	ret := _m.Called(table, key, command)

	if len(ret) == 0 {
		panic("no return value specified for BindKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(table, key, command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigurator_BindKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindKey'
type MockConfigurator_BindKey_Call struct {
	*mock.Call
}

// BindKey is a helper method to define mock.On call
//   - table string
//   - key string
//   - command string
func (_e *MockConfigurator_Expecter) BindKey(table interface{}, key interface{}, command interface{}) *MockConfigurator_BindKey_Call {
	return &MockConfigurator_BindKey_Call{Call: _e.mock.On("BindKey", table, key, command)}
}

func (_c *MockConfigurator_BindKey_Call) Run(run func(table string, key string, command string)) *MockConfigurator_BindKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockConfigurator_BindKey_Call) Return(_a0 error) *MockConfigurator_BindKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigurator_BindKey_Call) RunAndReturn(run func(string, string, string) error) *MockConfigurator_BindKey_Call {
	_c.Call.Return(run)
	return _c
}

// SourceFile provides a mock function with given fields: configPath
func (_m *MockConfigurator) SourceFile(configPath string) error {
	ret := _m.Called(configPath)

	if len(ret) == 0 {
		panic("no return value specified for SourceFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(configPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigurator_SourceFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SourceFile'
type MockConfigurator_SourceFile_Call struct {
	*mock.Call
}

// SourceFile is a helper method to define mock.On call
//   - configPath string
func (_e *MockConfigurator_Expecter) SourceFile(configPath interface{}) *MockConfigurator_SourceFile_Call {
	return &MockConfigurator_SourceFile_Call{Call: _e.mock.On("SourceFile", configPath)}
}

func (_c *MockConfigurator_SourceFile_Call) Run(run func(configPath string)) *MockConfigurator_SourceFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigurator_SourceFile_Call) Return(_a0 error) *MockConfigurator_SourceFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigurator_SourceFile_Call) RunAndReturn(run func(string) error) *MockConfigurator_SourceFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigurator creates a new instance of MockConfigurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigurator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigurator {
	mock := &MockConfigurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
