// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/renato0307/rocha/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGitRepository creates a new instance of MockGitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitRepository {
	mock := &MockGitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitRepository is an autogenerated mock type for the GitRepository type
type MockGitRepository struct {
	mock.Mock
}

type MockGitRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitRepository) EXPECT() *MockGitRepository_Expecter {
	return &MockGitRepository_Expecter{mock: &_m.Mock}
}

// BuildWorktreePath provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) BuildWorktreePath(base string, repoInfo string, sessionName string) string {
	ret := _mock.Called(base, repoInfo, sessionName)

	if len(ret) == 0 {
		panic("no return value specified for BuildWorktreePath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = returnFunc(base, repoInfo, sessionName)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGitRepository_BuildWorktreePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildWorktreePath'
type MockGitRepository_BuildWorktreePath_Call struct {
	*mock.Call
}

// BuildWorktreePath is a helper method to define mock.On call
//   - base string
//   - repoInfo string
//   - sessionName string
func (_e *MockGitRepository_Expecter) BuildWorktreePath(base interface{}, repoInfo interface{}, sessionName interface{}) *MockGitRepository_BuildWorktreePath_Call {
	return &MockGitRepository_BuildWorktreePath_Call{Call: _e.mock.On("BuildWorktreePath", base, repoInfo, sessionName)}
}

func (_c *MockGitRepository_BuildWorktreePath_Call) Run(run func(base string, repoInfo string, sessionName string)) *MockGitRepository_BuildWorktreePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitRepository_BuildWorktreePath_Call) Return(s string) *MockGitRepository_BuildWorktreePath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGitRepository_BuildWorktreePath_Call) RunAndReturn(run func(base string, repoInfo string, sessionName string) string) *MockGitRepository_BuildWorktreePath_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorktree provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) CreateWorktree(repoPath string, worktreePath string, branchName string) error {
	ret := _mock.Called(repoPath, worktreePath, branchName)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorktree")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(repoPath, worktreePath, branchName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitRepository_CreateWorktree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorktree'
type MockGitRepository_CreateWorktree_Call struct {
	*mock.Call
}

// CreateWorktree is a helper method to define mock.On call
//   - repoPath string
//   - worktreePath string
//   - branchName string
func (_e *MockGitRepository_Expecter) CreateWorktree(repoPath interface{}, worktreePath interface{}, branchName interface{}) *MockGitRepository_CreateWorktree_Call {
	return &MockGitRepository_CreateWorktree_Call{Call: _e.mock.On("CreateWorktree", repoPath, worktreePath, branchName)}
}

func (_c *MockGitRepository_CreateWorktree_Call) Run(run func(repoPath string, worktreePath string, branchName string)) *MockGitRepository_CreateWorktree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitRepository_CreateWorktree_Call) Return(err error) *MockGitRepository_CreateWorktree_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitRepository_CreateWorktree_Call) RunAndReturn(run func(repoPath string, worktreePath string, branchName string) error) *MockGitRepository_CreateWorktree_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAllPRs provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) FetchAllPRs(ctx context.Context, repoPath string) (map[string]*domain.PRInfo, error) {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for FetchAllPRs")
	}

	var r0 map[string]*domain.PRInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]*domain.PRInfo, error)); ok {
		return returnFunc(ctx, repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]*domain.PRInfo); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*domain.PRInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitRepository_FetchAllPRs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAllPRs'
type MockGitRepository_FetchAllPRs_Call struct {
	*mock.Call
}

// FetchAllPRs is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockGitRepository_Expecter) FetchAllPRs(ctx interface{}, repoPath interface{}) *MockGitRepository_FetchAllPRs_Call {
	return &MockGitRepository_FetchAllPRs_Call{Call: _e.mock.On("FetchAllPRs", ctx, repoPath)}
}

func (_c *MockGitRepository_FetchAllPRs_Call) Run(run func(ctx context.Context, repoPath string)) *MockGitRepository_FetchAllPRs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitRepository_FetchAllPRs_Call) Return(stringToPRInfo map[string]*domain.PRInfo, err error) *MockGitRepository_FetchAllPRs_Call {
	_c.Call.Return(stringToPRInfo, err)
	return _c
}

func (_c *MockGitRepository_FetchAllPRs_Call) RunAndReturn(run func(ctx context.Context, repoPath string) (map[string]*domain.PRInfo, error)) *MockGitRepository_FetchAllPRs_Call {
	_c.Call.Return(run)
	return _c
}

// FetchGitStats provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) FetchGitStats(ctx context.Context, worktreePath string) (*domain.GitStats, error) {
	ret := _mock.Called(ctx, worktreePath)

	if len(ret) == 0 {
		panic("no return value specified for FetchGitStats")
	}

	var r0 *domain.GitStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.GitStats, error)); ok {
		return returnFunc(ctx, worktreePath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.GitStats); ok {
		r0 = returnFunc(ctx, worktreePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GitStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, worktreePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitRepository_FetchGitStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchGitStats'
type MockGitRepository_FetchGitStats_Call struct {
	*mock.Call
}

// FetchGitStats is a helper method to define mock.On call
//   - ctx context.Context
//   - worktreePath string
func (_e *MockGitRepository_Expecter) FetchGitStats(ctx interface{}, worktreePath interface{}) *MockGitRepository_FetchGitStats_Call {
	return &MockGitRepository_FetchGitStats_Call{Call: _e.mock.On("FetchGitStats", ctx, worktreePath)}
}

func (_c *MockGitRepository_FetchGitStats_Call) Run(run func(ctx context.Context, worktreePath string)) *MockGitRepository_FetchGitStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitRepository_FetchGitStats_Call) Return(gitStats *domain.GitStats, err error) *MockGitRepository_FetchGitStats_Call {
	_c.Call.Return(gitStats, err)
	return _c
}

func (_c *MockGitRepository_FetchGitStats_Call) RunAndReturn(run func(ctx context.Context, worktreePath string) (*domain.GitStats, error)) *MockGitRepository_FetchGitStats_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPRInfo provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) FetchPRInfo(ctx context.Context, worktreePath string, branchName string) (*domain.PRInfo, error) {
	ret := _mock.Called(ctx, worktreePath, branchName)

	if len(ret) == 0 {
		panic("no return value specified for FetchPRInfo")
	}

	var r0 *domain.PRInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.PRInfo, error)); ok {
		return returnFunc(ctx, worktreePath, branchName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.PRInfo); ok {
		r0 = returnFunc(ctx, worktreePath, branchName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PRInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, worktreePath, branchName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitRepository_FetchPRInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPRInfo'
type MockGitRepository_FetchPRInfo_Call struct {
	*mock.Call
}

// FetchPRInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - worktreePath string
//   - branchName string
func (_e *MockGitRepository_Expecter) FetchPRInfo(ctx interface{}, worktreePath interface{}, branchName interface{}) *MockGitRepository_FetchPRInfo_Call {
	return &MockGitRepository_FetchPRInfo_Call{Call: _e.mock.On("FetchPRInfo", ctx, worktreePath, branchName)}
}

func (_c *MockGitRepository_FetchPRInfo_Call) Run(run func(ctx context.Context, worktreePath string, branchName string)) *MockGitRepository_FetchPRInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitRepository_FetchPRInfo_Call) Return(pRInfo *domain.PRInfo, err error) *MockGitRepository_FetchPRInfo_Call {
	_c.Call.Return(pRInfo, err)
	return _c
}

func (_c *MockGitRepository_FetchPRInfo_Call) RunAndReturn(run func(ctx context.Context, worktreePath string, branchName string) (*domain.PRInfo, error)) *MockGitRepository_FetchPRInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetBranchName provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) GetBranchName(path string) string {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetBranchName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGitRepository_GetBranchName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBranchName'
type MockGitRepository_GetBranchName_Call struct {
	*mock.Call
}

// GetBranchName is a helper method to define mock.On call
//   - path string
func (_e *MockGitRepository_Expecter) GetBranchName(path interface{}) *MockGitRepository_GetBranchName_Call {
	return &MockGitRepository_GetBranchName_Call{Call: _e.mock.On("GetBranchName", path)}
}

func (_c *MockGitRepository_GetBranchName_Call) Run(run func(path string)) *MockGitRepository_GetBranchName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitRepository_GetBranchName_Call) Return(s string) *MockGitRepository_GetBranchName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGitRepository_GetBranchName_Call) RunAndReturn(run func(path string) string) *MockGitRepository_GetBranchName_Call {
	_c.Call.Return(run)
	return _c
}

// GetMainRepoPath provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) GetMainRepoPath(path string) (string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetMainRepoPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitRepository_GetMainRepoPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMainRepoPath'
type MockGitRepository_GetMainRepoPath_Call struct {
	*mock.Call
}

// GetMainRepoPath is a helper method to define mock.On call
//   - path string
func (_e *MockGitRepository_Expecter) GetMainRepoPath(path interface{}) *MockGitRepository_GetMainRepoPath_Call {
	return &MockGitRepository_GetMainRepoPath_Call{Call: _e.mock.On("GetMainRepoPath", path)}
}

func (_c *MockGitRepository_GetMainRepoPath_Call) Run(run func(path string)) *MockGitRepository_GetMainRepoPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitRepository_GetMainRepoPath_Call) Return(s string, err error) *MockGitRepository_GetMainRepoPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitRepository_GetMainRepoPath_Call) RunAndReturn(run func(path string) (string, error)) *MockGitRepository_GetMainRepoPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCloneRepository provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) GetOrCloneRepository(source string, worktreeBase string) (string, *domain.RepoSource, error) {
	ret := _mock.Called(source, worktreeBase)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCloneRepository")
	}

	var r0 string
	var r1 *domain.RepoSource
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, *domain.RepoSource, error)); ok {
		return returnFunc(source, worktreeBase)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(source, worktreeBase)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) *domain.RepoSource); ok {
		r1 = returnFunc(source, worktreeBase)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.RepoSource)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = returnFunc(source, worktreeBase)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGitRepository_GetOrCloneRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCloneRepository'
type MockGitRepository_GetOrCloneRepository_Call struct {
	*mock.Call
}

// GetOrCloneRepository is a helper method to define mock.On call
//   - source string
//   - worktreeBase string
func (_e *MockGitRepository_Expecter) GetOrCloneRepository(source interface{}, worktreeBase interface{}) *MockGitRepository_GetOrCloneRepository_Call {
	return &MockGitRepository_GetOrCloneRepository_Call{Call: _e.mock.On("GetOrCloneRepository", source, worktreeBase)}
}

func (_c *MockGitRepository_GetOrCloneRepository_Call) Run(run func(source string, worktreeBase string)) *MockGitRepository_GetOrCloneRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitRepository_GetOrCloneRepository_Call) Return(s string, repoSource *domain.RepoSource, err error) *MockGitRepository_GetOrCloneRepository_Call {
	_c.Call.Return(s, repoSource, err)
	return _c
}

func (_c *MockGitRepository_GetOrCloneRepository_Call) RunAndReturn(run func(source string, worktreeBase string) (string, *domain.RepoSource, error)) *MockGitRepository_GetOrCloneRepository_Call {
	_c.Call.Return(run)
	return _c
}

// GetRemoteURL provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) GetRemoteURL(repoPath string) string {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for GetRemoteURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(repoPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGitRepository_GetRemoteURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRemoteURL'
type MockGitRepository_GetRemoteURL_Call struct {
	*mock.Call
}

// GetRemoteURL is a helper method to define mock.On call
//   - repoPath string
func (_e *MockGitRepository_Expecter) GetRemoteURL(repoPath interface{}) *MockGitRepository_GetRemoteURL_Call {
	return &MockGitRepository_GetRemoteURL_Call{Call: _e.mock.On("GetRemoteURL", repoPath)}
}

func (_c *MockGitRepository_GetRemoteURL_Call) Run(run func(repoPath string)) *MockGitRepository_GetRemoteURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitRepository_GetRemoteURL_Call) Return(s string) *MockGitRepository_GetRemoteURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGitRepository_GetRemoteURL_Call) RunAndReturn(run func(repoPath string) string) *MockGitRepository_GetRemoteURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepoInfo provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) GetRepoInfo(repoPath string) string {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for GetRepoInfo")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(repoPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGitRepository_GetRepoInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoInfo'
type MockGitRepository_GetRepoInfo_Call struct {
	*mock.Call
}

// GetRepoInfo is a helper method to define mock.On call
//   - repoPath string
func (_e *MockGitRepository_Expecter) GetRepoInfo(repoPath interface{}) *MockGitRepository_GetRepoInfo_Call {
	return &MockGitRepository_GetRepoInfo_Call{Call: _e.mock.On("GetRepoInfo", repoPath)}
}

func (_c *MockGitRepository_GetRepoInfo_Call) Run(run func(repoPath string)) *MockGitRepository_GetRepoInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitRepository_GetRepoInfo_Call) Return(s string) *MockGitRepository_GetRepoInfo_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGitRepository_GetRepoInfo_Call) RunAndReturn(run func(repoPath string) string) *MockGitRepository_GetRepoInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorktreeForBranch provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) GetWorktreeForBranch(repoPath string, branchName string) (string, error) {
	ret := _mock.Called(repoPath, branchName)

	if len(ret) == 0 {
		panic("no return value specified for GetWorktreeForBranch")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(repoPath, branchName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(repoPath, branchName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(repoPath, branchName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitRepository_GetWorktreeForBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorktreeForBranch'
type MockGitRepository_GetWorktreeForBranch_Call struct {
	*mock.Call
}

// GetWorktreeForBranch is a helper method to define mock.On call
//   - repoPath string
//   - branchName string
func (_e *MockGitRepository_Expecter) GetWorktreeForBranch(repoPath interface{}, branchName interface{}) *MockGitRepository_GetWorktreeForBranch_Call {
	return &MockGitRepository_GetWorktreeForBranch_Call{Call: _e.mock.On("GetWorktreeForBranch", repoPath, branchName)}
}

func (_c *MockGitRepository_GetWorktreeForBranch_Call) Run(run func(repoPath string, branchName string)) *MockGitRepository_GetWorktreeForBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitRepository_GetWorktreeForBranch_Call) Return(s string, err error) *MockGitRepository_GetWorktreeForBranch_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitRepository_GetWorktreeForBranch_Call) RunAndReturn(run func(repoPath string, branchName string) (string, error)) *MockGitRepository_GetWorktreeForBranch_Call {
	_c.Call.Return(run)
	return _c
}

// IsGitRepo provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) IsGitRepo(path string) (bool, string) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsGitRepo")
	}

	var r0 bool
	var r1 string
	if returnFunc, ok := ret.Get(0).(func(string) (bool, string)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) string); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// MockGitRepository_IsGitRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsGitRepo'
type MockGitRepository_IsGitRepo_Call struct {
	*mock.Call
}

// IsGitRepo is a helper method to define mock.On call
//   - path string
func (_e *MockGitRepository_Expecter) IsGitRepo(path interface{}) *MockGitRepository_IsGitRepo_Call {
	return &MockGitRepository_IsGitRepo_Call{Call: _e.mock.On("IsGitRepo", path)}
}

func (_c *MockGitRepository_IsGitRepo_Call) Run(run func(path string)) *MockGitRepository_IsGitRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitRepository_IsGitRepo_Call) Return(b bool, s string) *MockGitRepository_IsGitRepo_Call {
	_c.Call.Return(b, s)
	return _c
}

func (_c *MockGitRepository_IsGitRepo_Call) RunAndReturn(run func(path string) (bool, string)) *MockGitRepository_IsGitRepo_Call {
	_c.Call.Return(run)
	return _c
}

// IsGitURL provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) IsGitURL(source string) bool {
	ret := _mock.Called(source)

	if len(ret) == 0 {
		panic("no return value specified for IsGitURL")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(source)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGitRepository_IsGitURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsGitURL'
type MockGitRepository_IsGitURL_Call struct {
	*mock.Call
}

// IsGitURL is a helper method to define mock.On call
//   - source string
func (_e *MockGitRepository_Expecter) IsGitURL(source interface{}) *MockGitRepository_IsGitURL_Call {
	return &MockGitRepository_IsGitURL_Call{Call: _e.mock.On("IsGitURL", source)}
}

func (_c *MockGitRepository_IsGitURL_Call) Run(run func(source string)) *MockGitRepository_IsGitURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitRepository_IsGitURL_Call) Return(b bool) *MockGitRepository_IsGitURL_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGitRepository_IsGitURL_Call) RunAndReturn(run func(source string) bool) *MockGitRepository_IsGitURL_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorktrees provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) ListWorktrees(repoPath string) ([]string, error) {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for ListWorktrees")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(repoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitRepository_ListWorktrees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorktrees'
type MockGitRepository_ListWorktrees_Call struct {
	*mock.Call
}

// ListWorktrees is a helper method to define mock.On call
//   - repoPath string
func (_e *MockGitRepository_Expecter) ListWorktrees(repoPath interface{}) *MockGitRepository_ListWorktrees_Call {
	return &MockGitRepository_ListWorktrees_Call{Call: _e.mock.On("ListWorktrees", repoPath)}
}

func (_c *MockGitRepository_ListWorktrees_Call) Run(run func(repoPath string)) *MockGitRepository_ListWorktrees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitRepository_ListWorktrees_Call) Return(strings []string, err error) *MockGitRepository_ListWorktrees_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGitRepository_ListWorktrees_Call) RunAndReturn(run func(repoPath string) ([]string, error)) *MockGitRepository_ListWorktrees_Call {
	_c.Call.Return(run)
	return _c
}

// OpenPRInBrowser provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) OpenPRInBrowser(worktreePath string) error {
	ret := _mock.Called(worktreePath)

	if len(ret) == 0 {
		panic("no return value specified for OpenPRInBrowser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(worktreePath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitRepository_OpenPRInBrowser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenPRInBrowser'
type MockGitRepository_OpenPRInBrowser_Call struct {
	*mock.Call
}

// OpenPRInBrowser is a helper method to define mock.On call
//   - worktreePath string
func (_e *MockGitRepository_Expecter) OpenPRInBrowser(worktreePath interface{}) *MockGitRepository_OpenPRInBrowser_Call {
	return &MockGitRepository_OpenPRInBrowser_Call{Call: _e.mock.On("OpenPRInBrowser", worktreePath)}
}

func (_c *MockGitRepository_OpenPRInBrowser_Call) Run(run func(worktreePath string)) *MockGitRepository_OpenPRInBrowser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitRepository_OpenPRInBrowser_Call) Return(err error) *MockGitRepository_OpenPRInBrowser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitRepository_OpenPRInBrowser_Call) RunAndReturn(run func(worktreePath string) error) *MockGitRepository_OpenPRInBrowser_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRepoSource provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) ParseRepoSource(source string) (*domain.RepoSource, error) {
	ret := _mock.Called(source)

	if len(ret) == 0 {
		panic("no return value specified for ParseRepoSource")
	}

	var r0 *domain.RepoSource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.RepoSource, error)); ok {
		return returnFunc(source)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.RepoSource); ok {
		r0 = returnFunc(source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RepoSource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(source)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitRepository_ParseRepoSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRepoSource'
type MockGitRepository_ParseRepoSource_Call struct {
	*mock.Call
}

// ParseRepoSource is a helper method to define mock.On call
//   - source string
func (_e *MockGitRepository_Expecter) ParseRepoSource(source interface{}) *MockGitRepository_ParseRepoSource_Call {
	return &MockGitRepository_ParseRepoSource_Call{Call: _e.mock.On("ParseRepoSource", source)}
}

func (_c *MockGitRepository_ParseRepoSource_Call) Run(run func(source string)) *MockGitRepository_ParseRepoSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitRepository_ParseRepoSource_Call) Return(repoSource *domain.RepoSource, err error) *MockGitRepository_ParseRepoSource_Call {
	_c.Call.Return(repoSource, err)
	return _c
}

func (_c *MockGitRepository_ParseRepoSource_Call) RunAndReturn(run func(source string) (*domain.RepoSource, error)) *MockGitRepository_ParseRepoSource_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveWorktree provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) RemoveWorktree(repoPath string, worktreePath string) error {
	ret := _mock.Called(repoPath, worktreePath)

	if len(ret) == 0 {
		panic("no return value specified for RemoveWorktree")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(repoPath, worktreePath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitRepository_RemoveWorktree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveWorktree'
type MockGitRepository_RemoveWorktree_Call struct {
	*mock.Call
}

// RemoveWorktree is a helper method to define mock.On call
//   - repoPath string
//   - worktreePath string
func (_e *MockGitRepository_Expecter) RemoveWorktree(repoPath interface{}, worktreePath interface{}) *MockGitRepository_RemoveWorktree_Call {
	return &MockGitRepository_RemoveWorktree_Call{Call: _e.mock.On("RemoveWorktree", repoPath, worktreePath)}
}

func (_c *MockGitRepository_RemoveWorktree_Call) Run(run func(repoPath string, worktreePath string)) *MockGitRepository_RemoveWorktree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitRepository_RemoveWorktree_Call) Return(err error) *MockGitRepository_RemoveWorktree_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitRepository_RemoveWorktree_Call) RunAndReturn(run func(repoPath string, worktreePath string) error) *MockGitRepository_RemoveWorktree_Call {
	_c.Call.Return(run)
	return _c
}

// RepairWorktrees provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) RepairWorktrees(mainRepoPath string, worktreePaths []string) error {
	ret := _mock.Called(mainRepoPath, worktreePaths)

	if len(ret) == 0 {
		panic("no return value specified for RepairWorktrees")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = returnFunc(mainRepoPath, worktreePaths)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitRepository_RepairWorktrees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepairWorktrees'
type MockGitRepository_RepairWorktrees_Call struct {
	*mock.Call
}

// RepairWorktrees is a helper method to define mock.On call
//   - mainRepoPath string
//   - worktreePaths []string
func (_e *MockGitRepository_Expecter) RepairWorktrees(mainRepoPath interface{}, worktreePaths interface{}) *MockGitRepository_RepairWorktrees_Call {
	return &MockGitRepository_RepairWorktrees_Call{Call: _e.mock.On("RepairWorktrees", mainRepoPath, worktreePaths)}
}

func (_c *MockGitRepository_RepairWorktrees_Call) Run(run func(mainRepoPath string, worktreePaths []string)) *MockGitRepository_RepairWorktrees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitRepository_RepairWorktrees_Call) Return(err error) *MockGitRepository_RepairWorktrees_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitRepository_RepairWorktrees_Call) RunAndReturn(run func(mainRepoPath string, worktreePaths []string) error) *MockGitRepository_RepairWorktrees_Call {
	_c.Call.Return(run)
	return _c
}

// SanitizeBranchName provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) SanitizeBranchName(name string) (string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for SanitizeBranchName")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitRepository_SanitizeBranchName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SanitizeBranchName'
type MockGitRepository_SanitizeBranchName_Call struct {
	*mock.Call
}

// SanitizeBranchName is a helper method to define mock.On call
//   - name string
func (_e *MockGitRepository_Expecter) SanitizeBranchName(name interface{}) *MockGitRepository_SanitizeBranchName_Call {
	return &MockGitRepository_SanitizeBranchName_Call{Call: _e.mock.On("SanitizeBranchName", name)}
}

func (_c *MockGitRepository_SanitizeBranchName_Call) Run(run func(name string)) *MockGitRepository_SanitizeBranchName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitRepository_SanitizeBranchName_Call) Return(s string, err error) *MockGitRepository_SanitizeBranchName_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitRepository_SanitizeBranchName_Call) RunAndReturn(run func(name string) (string, error)) *MockGitRepository_SanitizeBranchName_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateBranchName provides a mock function for the type MockGitRepository
func (_mock *MockGitRepository) ValidateBranchName(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ValidateBranchName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitRepository_ValidateBranchName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateBranchName'
type MockGitRepository_ValidateBranchName_Call struct {
	*mock.Call
}

// ValidateBranchName is a helper method to define mock.On call
//   - name string
func (_e *MockGitRepository_Expecter) ValidateBranchName(name interface{}) *MockGitRepository_ValidateBranchName_Call {
	return &MockGitRepository_ValidateBranchName_Call{Call: _e.mock.On("ValidateBranchName", name)}
}

func (_c *MockGitRepository_ValidateBranchName_Call) Run(run func(name string)) *MockGitRepository_ValidateBranchName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitRepository_ValidateBranchName_Call) Return(err error) *MockGitRepository_ValidateBranchName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitRepository_ValidateBranchName_Call) RunAndReturn(run func(name string) error) *MockGitRepository_ValidateBranchName_Call {
	_c.Call.Return(run)
	return _c
}
