// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/renato0307/rocha/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionReader creates a new instance of MockSessionReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionReader {
	mock := &MockSessionReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionReader is an autogenerated mock type for the SessionReader type
type MockSessionReader struct {
	mock.Mock
}

type MockSessionReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionReader) EXPECT() *MockSessionReader_Expecter {
	return &MockSessionReader_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockSessionReader
func (_mock *MockSessionReader) Get(ctx context.Context, name string) (*domain.Session, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Session, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Session); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSessionReader_Expecter) Get(ctx interface{}, name interface{}) *MockSessionReader_Get_Call {
	return &MockSessionReader_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockSessionReader_Get_Call) Run(run func(ctx context.Context, name string)) *MockSessionReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionReader_Get_Call) Return(session *domain.Session, err error) *MockSessionReader_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionReader_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (*domain.Session, error)) *MockSessionReader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSessionReader
func (_mock *MockSessionReader) List(ctx context.Context, includeArchived bool) ([]domain.Session, error) {
	ret := _mock.Called(ctx, includeArchived)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) ([]domain.Session, error)); ok {
		return returnFunc(ctx, includeArchived)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) []domain.Session); ok {
		r0 = returnFunc(ctx, includeArchived)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, includeArchived)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionReader_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSessionReader_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - includeArchived bool
func (_e *MockSessionReader_Expecter) List(ctx interface{}, includeArchived interface{}) *MockSessionReader_List_Call {
	return &MockSessionReader_List_Call{Call: _e.mock.On("List", ctx, includeArchived)}
}

func (_c *MockSessionReader_List_Call) Run(run func(ctx context.Context, includeArchived bool)) *MockSessionReader_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionReader_List_Call) Return(sessions []domain.Session, err error) *MockSessionReader_List_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *MockSessionReader_List_Call) RunAndReturn(run func(ctx context.Context, includeArchived bool) ([]domain.Session, error)) *MockSessionReader_List_Call {
	_c.Call.Return(run)
	return _c
}
