// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProcessInspector creates a new instance of MockProcessInspector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessInspector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessInspector {
	mock := &MockProcessInspector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcessInspector is an autogenerated mock type for the ProcessInspector type
type MockProcessInspector struct {
	mock.Mock
}

type MockProcessInspector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessInspector) EXPECT() *MockProcessInspector_Expecter {
	return &MockProcessInspector_Expecter{mock: &_m.Mock}
}

// GetClaudeSettings provides a mock function for the type MockProcessInspector
func (_mock *MockProcessInspector) GetClaudeSettings(sessionName string) (string, error) {
	ret := _mock.Called(sessionName)

	if len(ret) == 0 {
		panic("no return value specified for GetClaudeSettings")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(sessionName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(sessionName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(sessionName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessInspector_GetClaudeSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaudeSettings'
type MockProcessInspector_GetClaudeSettings_Call struct {
	*mock.Call
}

// GetClaudeSettings is a helper method to define mock.On call
//   - sessionName string
func (_e *MockProcessInspector_Expecter) GetClaudeSettings(sessionName interface{}) *MockProcessInspector_GetClaudeSettings_Call {
	return &MockProcessInspector_GetClaudeSettings_Call{Call: _e.mock.On("GetClaudeSettings", sessionName)}
}

func (_c *MockProcessInspector_GetClaudeSettings_Call) Run(run func(sessionName string)) *MockProcessInspector_GetClaudeSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcessInspector_GetClaudeSettings_Call) Return(s string, err error) *MockProcessInspector_GetClaudeSettings_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockProcessInspector_GetClaudeSettings_Call) RunAndReturn(run func(sessionName string) (string, error)) *MockProcessInspector_GetClaudeSettings_Call {
	_c.Call.Return(run)
	return _c
}
