// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/renato0307/rocha/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTmuxSessionLifecycle creates a new instance of MockTmuxSessionLifecycle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTmuxSessionLifecycle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTmuxSessionLifecycle {
	mock := &MockTmuxSessionLifecycle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTmuxSessionLifecycle is an autogenerated mock type for the TmuxSessionLifecycle type
type MockTmuxSessionLifecycle struct {
	mock.Mock
}

type MockTmuxSessionLifecycle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTmuxSessionLifecycle) EXPECT() *MockTmuxSessionLifecycle_Expecter {
	return &MockTmuxSessionLifecycle_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockTmuxSessionLifecycle
func (_mock *MockTmuxSessionLifecycle) CreateSession(name string, worktreePath string, claudeDir string, statusPosition string, initialPrompt string) (*ports.TmuxSession, error) {
	ret := _mock.Called(name, worktreePath, claudeDir, statusPosition, initialPrompt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *ports.TmuxSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string) (*ports.TmuxSession, error)); ok {
		return returnFunc(name, worktreePath, claudeDir, statusPosition, initialPrompt)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string) *ports.TmuxSession); ok {
		r0 = returnFunc(name, worktreePath, claudeDir, statusPosition, initialPrompt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.TmuxSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, string, string) error); ok {
		r1 = returnFunc(name, worktreePath, claudeDir, statusPosition, initialPrompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxSessionLifecycle_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockTmuxSessionLifecycle_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - name string
//   - worktreePath string
//   - claudeDir string
//   - statusPosition string
//   - initialPrompt string
func (_e *MockTmuxSessionLifecycle_Expecter) CreateSession(name interface{}, worktreePath interface{}, claudeDir interface{}, statusPosition interface{}, initialPrompt interface{}) *MockTmuxSessionLifecycle_CreateSession_Call {
	return &MockTmuxSessionLifecycle_CreateSession_Call{Call: _e.mock.On("CreateSession", name, worktreePath, claudeDir, statusPosition, initialPrompt)}
}

func (_c *MockTmuxSessionLifecycle_CreateSession_Call) Run(run func(name string, worktreePath string, claudeDir string, statusPosition string, initialPrompt string)) *MockTmuxSessionLifecycle_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTmuxSessionLifecycle_CreateSession_Call) Return(tmuxSession *ports.TmuxSession, err error) *MockTmuxSessionLifecycle_CreateSession_Call {
	_c.Call.Return(tmuxSession, err)
	return _c
}

func (_c *MockTmuxSessionLifecycle_CreateSession_Call) RunAndReturn(run func(name string, worktreePath string, claudeDir string, statusPosition string, initialPrompt string) (*ports.TmuxSession, error)) *MockTmuxSessionLifecycle_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShellSession provides a mock function for the type MockTmuxSessionLifecycle
func (_mock *MockTmuxSessionLifecycle) CreateShellSession(name string, worktreePath string, statusPosition string) (*ports.TmuxSession, error) {
	ret := _mock.Called(name, worktreePath, statusPosition)

	if len(ret) == 0 {
		panic("no return value specified for CreateShellSession")
	}

	var r0 *ports.TmuxSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*ports.TmuxSession, error)); ok {
		return returnFunc(name, worktreePath, statusPosition)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *ports.TmuxSession); ok {
		r0 = returnFunc(name, worktreePath, statusPosition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.TmuxSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(name, worktreePath, statusPosition)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxSessionLifecycle_CreateShellSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShellSession'
type MockTmuxSessionLifecycle_CreateShellSession_Call struct {
	*mock.Call
}

// CreateShellSession is a helper method to define mock.On call
//   - name string
//   - worktreePath string
//   - statusPosition string
func (_e *MockTmuxSessionLifecycle_Expecter) CreateShellSession(name interface{}, worktreePath interface{}, statusPosition interface{}) *MockTmuxSessionLifecycle_CreateShellSession_Call {
	return &MockTmuxSessionLifecycle_CreateShellSession_Call{Call: _e.mock.On("CreateShellSession", name, worktreePath, statusPosition)}
}

func (_c *MockTmuxSessionLifecycle_CreateShellSession_Call) Run(run func(name string, worktreePath string, statusPosition string)) *MockTmuxSessionLifecycle_CreateShellSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTmuxSessionLifecycle_CreateShellSession_Call) Return(tmuxSession *ports.TmuxSession, err error) *MockTmuxSessionLifecycle_CreateShellSession_Call {
	_c.Call.Return(tmuxSession, err)
	return _c
}

func (_c *MockTmuxSessionLifecycle_CreateShellSession_Call) RunAndReturn(run func(name string, worktreePath string, statusPosition string) (*ports.TmuxSession, error)) *MockTmuxSessionLifecycle_CreateShellSession_Call {
	_c.Call.Return(run)
	return _c
}

// KillSession provides a mock function for the type MockTmuxSessionLifecycle
func (_mock *MockTmuxSessionLifecycle) KillSession(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for KillSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxSessionLifecycle_KillSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillSession'
type MockTmuxSessionLifecycle_KillSession_Call struct {
	*mock.Call
}

// KillSession is a helper method to define mock.On call
//   - name string
func (_e *MockTmuxSessionLifecycle_Expecter) KillSession(name interface{}) *MockTmuxSessionLifecycle_KillSession_Call {
	return &MockTmuxSessionLifecycle_KillSession_Call{Call: _e.mock.On("KillSession", name)}
}

func (_c *MockTmuxSessionLifecycle_KillSession_Call) Run(run func(name string)) *MockTmuxSessionLifecycle_KillSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxSessionLifecycle_KillSession_Call) Return(err error) *MockTmuxSessionLifecycle_KillSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxSessionLifecycle_KillSession_Call) RunAndReturn(run func(name string) error) *MockTmuxSessionLifecycle_KillSession_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function for the type MockTmuxSessionLifecycle
func (_mock *MockTmuxSessionLifecycle) ListSessions() ([]*ports.TmuxSession, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []*ports.TmuxSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*ports.TmuxSession, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*ports.TmuxSession); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ports.TmuxSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxSessionLifecycle_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockTmuxSessionLifecycle_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
func (_e *MockTmuxSessionLifecycle_Expecter) ListSessions() *MockTmuxSessionLifecycle_ListSessions_Call {
	return &MockTmuxSessionLifecycle_ListSessions_Call{Call: _e.mock.On("ListSessions")}
}

func (_c *MockTmuxSessionLifecycle_ListSessions_Call) Run(run func()) *MockTmuxSessionLifecycle_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTmuxSessionLifecycle_ListSessions_Call) Return(tmuxSessions []*ports.TmuxSession, err error) *MockTmuxSessionLifecycle_ListSessions_Call {
	_c.Call.Return(tmuxSessions, err)
	return _c
}

func (_c *MockTmuxSessionLifecycle_ListSessions_Call) RunAndReturn(run func() ([]*ports.TmuxSession, error)) *MockTmuxSessionLifecycle_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RenameSession provides a mock function for the type MockTmuxSessionLifecycle
func (_mock *MockTmuxSessionLifecycle) RenameSession(oldName string, newName string) error {
	ret := _mock.Called(oldName, newName)

	if len(ret) == 0 {
		panic("no return value specified for RenameSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(oldName, newName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxSessionLifecycle_RenameSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameSession'
type MockTmuxSessionLifecycle_RenameSession_Call struct {
	*mock.Call
}

// RenameSession is a helper method to define mock.On call
//   - oldName string
//   - newName string
func (_e *MockTmuxSessionLifecycle_Expecter) RenameSession(oldName interface{}, newName interface{}) *MockTmuxSessionLifecycle_RenameSession_Call {
	return &MockTmuxSessionLifecycle_RenameSession_Call{Call: _e.mock.On("RenameSession", oldName, newName)}
}

func (_c *MockTmuxSessionLifecycle_RenameSession_Call) Run(run func(oldName string, newName string)) *MockTmuxSessionLifecycle_RenameSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxSessionLifecycle_RenameSession_Call) Return(err error) *MockTmuxSessionLifecycle_RenameSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxSessionLifecycle_RenameSession_Call) RunAndReturn(run func(oldName string, newName string) error) *MockTmuxSessionLifecycle_RenameSession_Call {
	_c.Call.Return(run)
	return _c
}

// SessionExists provides a mock function for the type MockTmuxSessionLifecycle
func (_mock *MockTmuxSessionLifecycle) SessionExists(name string) bool {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for SessionExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTmuxSessionLifecycle_SessionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionExists'
type MockTmuxSessionLifecycle_SessionExists_Call struct {
	*mock.Call
}

// SessionExists is a helper method to define mock.On call
//   - name string
func (_e *MockTmuxSessionLifecycle_Expecter) SessionExists(name interface{}) *MockTmuxSessionLifecycle_SessionExists_Call {
	return &MockTmuxSessionLifecycle_SessionExists_Call{Call: _e.mock.On("SessionExists", name)}
}

func (_c *MockTmuxSessionLifecycle_SessionExists_Call) Run(run func(name string)) *MockTmuxSessionLifecycle_SessionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxSessionLifecycle_SessionExists_Call) Return(b bool) *MockTmuxSessionLifecycle_SessionExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTmuxSessionLifecycle_SessionExists_Call) RunAndReturn(run func(name string) bool) *MockTmuxSessionLifecycle_SessionExists_Call {
	_c.Call.Return(run)
	return _c
}
