// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/renato0307/rocha/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenUsageReader creates a new instance of MockTokenUsageReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenUsageReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenUsageReader {
	mock := &MockTokenUsageReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenUsageReader is an autogenerated mock type for the TokenUsageReader type
type MockTokenUsageReader struct {
	mock.Mock
}

type MockTokenUsageReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenUsageReader) EXPECT() *MockTokenUsageReader_Expecter {
	return &MockTokenUsageReader_Expecter{mock: &_m.Mock}
}

// GetTodayUsage provides a mock function for the type MockTokenUsageReader
func (_mock *MockTokenUsageReader) GetTodayUsage() ([]ports.TokenUsage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTodayUsage")
	}

	var r0 []ports.TokenUsage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]ports.TokenUsage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []ports.TokenUsage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.TokenUsage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenUsageReader_GetTodayUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodayUsage'
type MockTokenUsageReader_GetTodayUsage_Call struct {
	*mock.Call
}

// GetTodayUsage is a helper method to define mock.On call
func (_e *MockTokenUsageReader_Expecter) GetTodayUsage() *MockTokenUsageReader_GetTodayUsage_Call {
	return &MockTokenUsageReader_GetTodayUsage_Call{Call: _e.mock.On("GetTodayUsage")}
}

func (_c *MockTokenUsageReader_GetTodayUsage_Call) Run(run func()) *MockTokenUsageReader_GetTodayUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenUsageReader_GetTodayUsage_Call) Return(tokenUsages []ports.TokenUsage, err error) *MockTokenUsageReader_GetTodayUsage_Call {
	_c.Call.Return(tokenUsages, err)
	return _c
}

func (_c *MockTokenUsageReader_GetTodayUsage_Call) RunAndReturn(run func() ([]ports.TokenUsage, error)) *MockTokenUsageReader_GetTodayUsage_Call {
	_c.Call.Return(run)
	return _c
}
