// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os/exec"

	"github.com/renato0307/rocha/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTmuxClient creates a new instance of MockTmuxClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTmuxClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTmuxClient {
	mock := &MockTmuxClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTmuxClient is an autogenerated mock type for the TmuxClient type
type MockTmuxClient struct {
	mock.Mock
}

type MockTmuxClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTmuxClient) EXPECT() *MockTmuxClient_Expecter {
	return &MockTmuxClient_Expecter{mock: &_m.Mock}
}

// Attach provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) Attach(sessionName string) (chan struct{}, error) {
	ret := _mock.Called(sessionName)

	if len(ret) == 0 {
		panic("no return value specified for Attach")
	}

	var r0 chan struct{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (chan struct{}, error)); ok {
		return returnFunc(sessionName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) chan struct{}); ok {
		r0 = returnFunc(sessionName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan struct{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(sessionName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxClient_Attach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attach'
type MockTmuxClient_Attach_Call struct {
	*mock.Call
}

// Attach is a helper method to define mock.On call
//   - sessionName string
func (_e *MockTmuxClient_Expecter) Attach(sessionName interface{}) *MockTmuxClient_Attach_Call {
	return &MockTmuxClient_Attach_Call{Call: _e.mock.On("Attach", sessionName)}
}

func (_c *MockTmuxClient_Attach_Call) Run(run func(sessionName string)) *MockTmuxClient_Attach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxClient_Attach_Call) Return(valCh chan struct{}, err error) *MockTmuxClient_Attach_Call {
	_c.Call.Return(valCh, err)
	return _c
}

func (_c *MockTmuxClient_Attach_Call) RunAndReturn(run func(sessionName string) (chan struct{}, error)) *MockTmuxClient_Attach_Call {
	_c.Call.Return(run)
	return _c
}

// BindKey provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) BindKey(table string, key string, command string) error {
	ret := _mock.Called(table, key, command)

	if len(ret) == 0 {
		panic("no return value specified for BindKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(table, key, command)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxClient_BindKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindKey'
type MockTmuxClient_BindKey_Call struct {
	*mock.Call
}

// BindKey is a helper method to define mock.On call
//   - table string
//   - key string
//   - command string
func (_e *MockTmuxClient_Expecter) BindKey(table interface{}, key interface{}, command interface{}) *MockTmuxClient_BindKey_Call {
	return &MockTmuxClient_BindKey_Call{Call: _e.mock.On("BindKey", table, key, command)}
}

func (_c *MockTmuxClient_BindKey_Call) Run(run func(table string, key string, command string)) *MockTmuxClient_BindKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTmuxClient_BindKey_Call) Return(err error) *MockTmuxClient_BindKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxClient_BindKey_Call) RunAndReturn(run func(table string, key string, command string) error) *MockTmuxClient_BindKey_Call {
	_c.Call.Return(run)
	return _c
}

// CapturePane provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) CapturePane(sessionName string, startLine int) (string, error) {
	ret := _mock.Called(sessionName, startLine)

	if len(ret) == 0 {
		panic("no return value specified for CapturePane")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) (string, error)); ok {
		return returnFunc(sessionName, startLine)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) string); ok {
		r0 = returnFunc(sessionName, startLine)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(sessionName, startLine)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxClient_CapturePane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CapturePane'
type MockTmuxClient_CapturePane_Call struct {
	*mock.Call
}

// CapturePane is a helper method to define mock.On call
//   - sessionName string
//   - startLine int
func (_e *MockTmuxClient_Expecter) CapturePane(sessionName interface{}, startLine interface{}) *MockTmuxClient_CapturePane_Call {
	return &MockTmuxClient_CapturePane_Call{Call: _e.mock.On("CapturePane", sessionName, startLine)}
}

func (_c *MockTmuxClient_CapturePane_Call) Run(run func(sessionName string, startLine int)) *MockTmuxClient_CapturePane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxClient_CapturePane_Call) Return(s string, err error) *MockTmuxClient_CapturePane_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTmuxClient_CapturePane_Call) RunAndReturn(run func(sessionName string, startLine int) (string, error)) *MockTmuxClient_CapturePane_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) CreateSession(name string, worktreePath string, claudeDir string, statusPosition string, initialPrompt string) (*ports.TmuxSession, error) {
	ret := _mock.Called(name, worktreePath, claudeDir, statusPosition, initialPrompt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *ports.TmuxSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string) (*ports.TmuxSession, error)); ok {
		return returnFunc(name, worktreePath, claudeDir, statusPosition, initialPrompt)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string) *ports.TmuxSession); ok {
		r0 = returnFunc(name, worktreePath, claudeDir, statusPosition, initialPrompt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.TmuxSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, string, string) error); ok {
		r1 = returnFunc(name, worktreePath, claudeDir, statusPosition, initialPrompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxClient_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockTmuxClient_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - name string
//   - worktreePath string
//   - claudeDir string
//   - statusPosition string
//   - initialPrompt string
func (_e *MockTmuxClient_Expecter) CreateSession(name interface{}, worktreePath interface{}, claudeDir interface{}, statusPosition interface{}, initialPrompt interface{}) *MockTmuxClient_CreateSession_Call {
	return &MockTmuxClient_CreateSession_Call{Call: _e.mock.On("CreateSession", name, worktreePath, claudeDir, statusPosition, initialPrompt)}
}

func (_c *MockTmuxClient_CreateSession_Call) Run(run func(name string, worktreePath string, claudeDir string, statusPosition string, initialPrompt string)) *MockTmuxClient_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTmuxClient_CreateSession_Call) Return(tmuxSession *ports.TmuxSession, err error) *MockTmuxClient_CreateSession_Call {
	_c.Call.Return(tmuxSession, err)
	return _c
}

func (_c *MockTmuxClient_CreateSession_Call) RunAndReturn(run func(name string, worktreePath string, claudeDir string, statusPosition string, initialPrompt string) (*ports.TmuxSession, error)) *MockTmuxClient_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShellSession provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) CreateShellSession(name string, worktreePath string, statusPosition string) (*ports.TmuxSession, error) {
	ret := _mock.Called(name, worktreePath, statusPosition)

	if len(ret) == 0 {
		panic("no return value specified for CreateShellSession")
	}

	var r0 *ports.TmuxSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*ports.TmuxSession, error)); ok {
		return returnFunc(name, worktreePath, statusPosition)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *ports.TmuxSession); ok {
		r0 = returnFunc(name, worktreePath, statusPosition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.TmuxSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(name, worktreePath, statusPosition)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxClient_CreateShellSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShellSession'
type MockTmuxClient_CreateShellSession_Call struct {
	*mock.Call
}

// CreateShellSession is a helper method to define mock.On call
//   - name string
//   - worktreePath string
//   - statusPosition string
func (_e *MockTmuxClient_Expecter) CreateShellSession(name interface{}, worktreePath interface{}, statusPosition interface{}) *MockTmuxClient_CreateShellSession_Call {
	return &MockTmuxClient_CreateShellSession_Call{Call: _e.mock.On("CreateShellSession", name, worktreePath, statusPosition)}
}

func (_c *MockTmuxClient_CreateShellSession_Call) Run(run func(name string, worktreePath string, statusPosition string)) *MockTmuxClient_CreateShellSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTmuxClient_CreateShellSession_Call) Return(tmuxSession *ports.TmuxSession, err error) *MockTmuxClient_CreateShellSession_Call {
	_c.Call.Return(tmuxSession, err)
	return _c
}

func (_c *MockTmuxClient_CreateShellSession_Call) RunAndReturn(run func(name string, worktreePath string, statusPosition string) (*ports.TmuxSession, error)) *MockTmuxClient_CreateShellSession_Call {
	_c.Call.Return(run)
	return _c
}

// Detach provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) Detach(sessionName string) error {
	ret := _mock.Called(sessionName)

	if len(ret) == 0 {
		panic("no return value specified for Detach")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(sessionName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxClient_Detach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detach'
type MockTmuxClient_Detach_Call struct {
	*mock.Call
}

// Detach is a helper method to define mock.On call
//   - sessionName string
func (_e *MockTmuxClient_Expecter) Detach(sessionName interface{}) *MockTmuxClient_Detach_Call {
	return &MockTmuxClient_Detach_Call{Call: _e.mock.On("Detach", sessionName)}
}

func (_c *MockTmuxClient_Detach_Call) Run(run func(sessionName string)) *MockTmuxClient_Detach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxClient_Detach_Call) Return(err error) *MockTmuxClient_Detach_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxClient_Detach_Call) RunAndReturn(run func(sessionName string) error) *MockTmuxClient_Detach_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttachCommand provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) GetAttachCommand(sessionName string) *exec.Cmd {
	ret := _mock.Called(sessionName)

	if len(ret) == 0 {
		panic("no return value specified for GetAttachCommand")
	}

	var r0 *exec.Cmd
	if returnFunc, ok := ret.Get(0).(func(string) *exec.Cmd); ok {
		r0 = returnFunc(sessionName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}
	return r0
}

// MockTmuxClient_GetAttachCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttachCommand'
type MockTmuxClient_GetAttachCommand_Call struct {
	*mock.Call
}

// GetAttachCommand is a helper method to define mock.On call
//   - sessionName string
func (_e *MockTmuxClient_Expecter) GetAttachCommand(sessionName interface{}) *MockTmuxClient_GetAttachCommand_Call {
	return &MockTmuxClient_GetAttachCommand_Call{Call: _e.mock.On("GetAttachCommand", sessionName)}
}

func (_c *MockTmuxClient_GetAttachCommand_Call) Run(run func(sessionName string)) *MockTmuxClient_GetAttachCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxClient_GetAttachCommand_Call) Return(cmd *exec.Cmd) *MockTmuxClient_GetAttachCommand_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockTmuxClient_GetAttachCommand_Call) RunAndReturn(run func(sessionName string) *exec.Cmd) *MockTmuxClient_GetAttachCommand_Call {
	_c.Call.Return(run)
	return _c
}

// KillSession provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) KillSession(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for KillSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxClient_KillSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillSession'
type MockTmuxClient_KillSession_Call struct {
	*mock.Call
}

// KillSession is a helper method to define mock.On call
//   - name string
func (_e *MockTmuxClient_Expecter) KillSession(name interface{}) *MockTmuxClient_KillSession_Call {
	return &MockTmuxClient_KillSession_Call{Call: _e.mock.On("KillSession", name)}
}

func (_c *MockTmuxClient_KillSession_Call) Run(run func(name string)) *MockTmuxClient_KillSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxClient_KillSession_Call) Return(err error) *MockTmuxClient_KillSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxClient_KillSession_Call) RunAndReturn(run func(name string) error) *MockTmuxClient_KillSession_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) ListSessions() ([]*ports.TmuxSession, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []*ports.TmuxSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*ports.TmuxSession, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*ports.TmuxSession); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ports.TmuxSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxClient_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockTmuxClient_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
func (_e *MockTmuxClient_Expecter) ListSessions() *MockTmuxClient_ListSessions_Call {
	return &MockTmuxClient_ListSessions_Call{Call: _e.mock.On("ListSessions")}
}

func (_c *MockTmuxClient_ListSessions_Call) Run(run func()) *MockTmuxClient_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTmuxClient_ListSessions_Call) Return(tmuxSessions []*ports.TmuxSession, err error) *MockTmuxClient_ListSessions_Call {
	_c.Call.Return(tmuxSessions, err)
	return _c
}

func (_c *MockTmuxClient_ListSessions_Call) RunAndReturn(run func() ([]*ports.TmuxSession, error)) *MockTmuxClient_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RenameSession provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) RenameSession(oldName string, newName string) error {
	ret := _mock.Called(oldName, newName)

	if len(ret) == 0 {
		panic("no return value specified for RenameSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(oldName, newName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxClient_RenameSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameSession'
type MockTmuxClient_RenameSession_Call struct {
	*mock.Call
}

// RenameSession is a helper method to define mock.On call
//   - oldName string
//   - newName string
func (_e *MockTmuxClient_Expecter) RenameSession(oldName interface{}, newName interface{}) *MockTmuxClient_RenameSession_Call {
	return &MockTmuxClient_RenameSession_Call{Call: _e.mock.On("RenameSession", oldName, newName)}
}

func (_c *MockTmuxClient_RenameSession_Call) Run(run func(oldName string, newName string)) *MockTmuxClient_RenameSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxClient_RenameSession_Call) Return(err error) *MockTmuxClient_RenameSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxClient_RenameSession_Call) RunAndReturn(run func(oldName string, newName string) error) *MockTmuxClient_RenameSession_Call {
	_c.Call.Return(run)
	return _c
}

// SendKeys provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) SendKeys(sessionName string, keys ...string) error {
	// string
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, sessionName)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SendKeys")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) error); ok {
		r0 = returnFunc(sessionName, keys...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxClient_SendKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendKeys'
type MockTmuxClient_SendKeys_Call struct {
	*mock.Call
}

// SendKeys is a helper method to define mock.On call
//   - sessionName string
//   - keys ...string
func (_e *MockTmuxClient_Expecter) SendKeys(sessionName interface{}, keys ...interface{}) *MockTmuxClient_SendKeys_Call {
	return &MockTmuxClient_SendKeys_Call{Call: _e.mock.On("SendKeys",
		append([]interface{}{sessionName}, keys...)...)}
}

func (_c *MockTmuxClient_SendKeys_Call) Run(run func(sessionName string, keys ...string)) *MockTmuxClient_SendKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTmuxClient_SendKeys_Call) Return(err error) *MockTmuxClient_SendKeys_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxClient_SendKeys_Call) RunAndReturn(run func(sessionName string, keys ...string) error) *MockTmuxClient_SendKeys_Call {
	_c.Call.Return(run)
	return _c
}

// SessionExists provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) SessionExists(name string) bool {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for SessionExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTmuxClient_SessionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionExists'
type MockTmuxClient_SessionExists_Call struct {
	*mock.Call
}

// SessionExists is a helper method to define mock.On call
//   - name string
func (_e *MockTmuxClient_Expecter) SessionExists(name interface{}) *MockTmuxClient_SessionExists_Call {
	return &MockTmuxClient_SessionExists_Call{Call: _e.mock.On("SessionExists", name)}
}

func (_c *MockTmuxClient_SessionExists_Call) Run(run func(name string)) *MockTmuxClient_SessionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxClient_SessionExists_Call) Return(b bool) *MockTmuxClient_SessionExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTmuxClient_SessionExists_Call) RunAndReturn(run func(name string) bool) *MockTmuxClient_SessionExists_Call {
	_c.Call.Return(run)
	return _c
}

// SetOption provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) SetOption(sessionName string, option string, value string) error {
	ret := _mock.Called(sessionName, option, value)

	if len(ret) == 0 {
		panic("no return value specified for SetOption")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(sessionName, option, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxClient_SetOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOption'
type MockTmuxClient_SetOption_Call struct {
	*mock.Call
}

// SetOption is a helper method to define mock.On call
//   - sessionName string
//   - option string
//   - value string
func (_e *MockTmuxClient_Expecter) SetOption(sessionName interface{}, option interface{}, value interface{}) *MockTmuxClient_SetOption_Call {
	return &MockTmuxClient_SetOption_Call{Call: _e.mock.On("SetOption", sessionName, option, value)}
}

func (_c *MockTmuxClient_SetOption_Call) Run(run func(sessionName string, option string, value string)) *MockTmuxClient_SetOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTmuxClient_SetOption_Call) Return(err error) *MockTmuxClient_SetOption_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxClient_SetOption_Call) RunAndReturn(run func(sessionName string, option string, value string) error) *MockTmuxClient_SetOption_Call {
	_c.Call.Return(run)
	return _c
}

// SourceFile provides a mock function for the type MockTmuxClient
func (_mock *MockTmuxClient) SourceFile(configPath string) error {
	ret := _mock.Called(configPath)

	if len(ret) == 0 {
		panic("no return value specified for SourceFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(configPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxClient_SourceFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SourceFile'
type MockTmuxClient_SourceFile_Call struct {
	*mock.Call
}

// SourceFile is a helper method to define mock.On call
//   - configPath string
func (_e *MockTmuxClient_Expecter) SourceFile(configPath interface{}) *MockTmuxClient_SourceFile_Call {
	return &MockTmuxClient_SourceFile_Call{Call: _e.mock.On("SourceFile", configPath)}
}

func (_c *MockTmuxClient_SourceFile_Call) Run(run func(configPath string)) *MockTmuxClient_SourceFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxClient_SourceFile_Call) Return(err error) *MockTmuxClient_SourceFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxClient_SourceFile_Call) RunAndReturn(run func(configPath string) error) *MockTmuxClient_SourceFile_Call {
	_c.Call.Return(run)
	return _c
}
