// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/renato0307/rocha/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionStateUpdater creates a new instance of MockSessionStateUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStateUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStateUpdater {
	mock := &MockSessionStateUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionStateUpdater is an autogenerated mock type for the SessionStateUpdater type
type MockSessionStateUpdater struct {
	mock.Mock
}

type MockSessionStateUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStateUpdater) EXPECT() *MockSessionStateUpdater_Expecter {
	return &MockSessionStateUpdater_Expecter{mock: &_m.Mock}
}

// UpdateClaudeDir provides a mock function for the type MockSessionStateUpdater
func (_mock *MockSessionStateUpdater) UpdateClaudeDir(ctx context.Context, name string, claudeDir string) error {
	ret := _mock.Called(ctx, name, claudeDir)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClaudeDir")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name, claudeDir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStateUpdater_UpdateClaudeDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClaudeDir'
type MockSessionStateUpdater_UpdateClaudeDir_Call struct {
	*mock.Call
}

// UpdateClaudeDir is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - claudeDir string
func (_e *MockSessionStateUpdater_Expecter) UpdateClaudeDir(ctx interface{}, name interface{}, claudeDir interface{}) *MockSessionStateUpdater_UpdateClaudeDir_Call {
	return &MockSessionStateUpdater_UpdateClaudeDir_Call{Call: _e.mock.On("UpdateClaudeDir", ctx, name, claudeDir)}
}

func (_c *MockSessionStateUpdater_UpdateClaudeDir_Call) Run(run func(ctx context.Context, name string, claudeDir string)) *MockSessionStateUpdater_UpdateClaudeDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionStateUpdater_UpdateClaudeDir_Call) Return(err error) *MockSessionStateUpdater_UpdateClaudeDir_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStateUpdater_UpdateClaudeDir_Call) RunAndReturn(run func(ctx context.Context, name string, claudeDir string) error) *MockSessionStateUpdater_UpdateClaudeDir_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRepoSource provides a mock function for the type MockSessionStateUpdater
func (_mock *MockSessionStateUpdater) UpdateRepoSource(ctx context.Context, name string, repoSource string) error {
	ret := _mock.Called(ctx, name, repoSource)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRepoSource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name, repoSource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStateUpdater_UpdateRepoSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRepoSource'
type MockSessionStateUpdater_UpdateRepoSource_Call struct {
	*mock.Call
}

// UpdateRepoSource is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - repoSource string
func (_e *MockSessionStateUpdater_Expecter) UpdateRepoSource(ctx interface{}, name interface{}, repoSource interface{}) *MockSessionStateUpdater_UpdateRepoSource_Call {
	return &MockSessionStateUpdater_UpdateRepoSource_Call{Call: _e.mock.On("UpdateRepoSource", ctx, name, repoSource)}
}

func (_c *MockSessionStateUpdater_UpdateRepoSource_Call) Run(run func(ctx context.Context, name string, repoSource string)) *MockSessionStateUpdater_UpdateRepoSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionStateUpdater_UpdateRepoSource_Call) Return(err error) *MockSessionStateUpdater_UpdateRepoSource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStateUpdater_UpdateRepoSource_Call) RunAndReturn(run func(ctx context.Context, name string, repoSource string) error) *MockSessionStateUpdater_UpdateRepoSource_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSkipPermissions provides a mock function for the type MockSessionStateUpdater
func (_mock *MockSessionStateUpdater) UpdateSkipPermissions(ctx context.Context, name string, skip bool) error {
	ret := _mock.Called(ctx, name, skip)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSkipPermissions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, name, skip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStateUpdater_UpdateSkipPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSkipPermissions'
type MockSessionStateUpdater_UpdateSkipPermissions_Call struct {
	*mock.Call
}

// UpdateSkipPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - skip bool
func (_e *MockSessionStateUpdater_Expecter) UpdateSkipPermissions(ctx interface{}, name interface{}, skip interface{}) *MockSessionStateUpdater_UpdateSkipPermissions_Call {
	return &MockSessionStateUpdater_UpdateSkipPermissions_Call{Call: _e.mock.On("UpdateSkipPermissions", ctx, name, skip)}
}

func (_c *MockSessionStateUpdater_UpdateSkipPermissions_Call) Run(run func(ctx context.Context, name string, skip bool)) *MockSessionStateUpdater_UpdateSkipPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionStateUpdater_UpdateSkipPermissions_Call) Return(err error) *MockSessionStateUpdater_UpdateSkipPermissions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStateUpdater_UpdateSkipPermissions_Call) RunAndReturn(run func(ctx context.Context, name string, skip bool) error) *MockSessionStateUpdater_UpdateSkipPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateState provides a mock function for the type MockSessionStateUpdater
func (_mock *MockSessionStateUpdater) UpdateState(ctx context.Context, name string, state domain.SessionState, executionID string) error {
	ret := _mock.Called(ctx, name, state, executionID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.SessionState, string) error); ok {
		r0 = returnFunc(ctx, name, state, executionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStateUpdater_UpdateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateState'
type MockSessionStateUpdater_UpdateState_Call struct {
	*mock.Call
}

// UpdateState is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - state domain.SessionState
//   - executionID string
func (_e *MockSessionStateUpdater_Expecter) UpdateState(ctx interface{}, name interface{}, state interface{}, executionID interface{}) *MockSessionStateUpdater_UpdateState_Call {
	return &MockSessionStateUpdater_UpdateState_Call{Call: _e.mock.On("UpdateState", ctx, name, state, executionID)}
}

func (_c *MockSessionStateUpdater_UpdateState_Call) Run(run func(ctx context.Context, name string, state domain.SessionState, executionID string)) *MockSessionStateUpdater_UpdateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.SessionState
		if args[2] != nil {
			arg2 = args[2].(domain.SessionState)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSessionStateUpdater_UpdateState_Call) Return(err error) *MockSessionStateUpdater_UpdateState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStateUpdater_UpdateState_Call) RunAndReturn(run func(ctx context.Context, name string, state domain.SessionState, executionID string) error) *MockSessionStateUpdater_UpdateState_Call {
	_c.Call.Return(run)
	return _c
}
