// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/renato0307/rocha/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionWriter creates a new instance of MockSessionWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionWriter {
	mock := &MockSessionWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionWriter is an autogenerated mock type for the SessionWriter type
type MockSessionWriter struct {
	mock.Mock
}

type MockSessionWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionWriter) EXPECT() *MockSessionWriter_Expecter {
	return &MockSessionWriter_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockSessionWriter
func (_mock *MockSessionWriter) Add(ctx context.Context, session domain.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionWriter_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockSessionWriter_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - session domain.Session
func (_e *MockSessionWriter_Expecter) Add(ctx interface{}, session interface{}) *MockSessionWriter_Add_Call {
	return &MockSessionWriter_Add_Call{Call: _e.mock.On("Add", ctx, session)}
}

func (_c *MockSessionWriter_Add_Call) Run(run func(ctx context.Context, session domain.Session)) *MockSessionWriter_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Session
		if args[1] != nil {
			arg1 = args[1].(domain.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionWriter_Add_Call) Return(err error) *MockSessionWriter_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionWriter_Add_Call) RunAndReturn(run func(ctx context.Context, session domain.Session) error) *MockSessionWriter_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSessionWriter
func (_mock *MockSessionWriter) Delete(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionWriter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionWriter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSessionWriter_Expecter) Delete(ctx interface{}, name interface{}) *MockSessionWriter_Delete_Call {
	return &MockSessionWriter_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockSessionWriter_Delete_Call) Run(run func(ctx context.Context, name string)) *MockSessionWriter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionWriter_Delete_Call) Return(err error) *MockSessionWriter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionWriter_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockSessionWriter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// LinkShellSession provides a mock function for the type MockSessionWriter
func (_mock *MockSessionWriter) LinkShellSession(ctx context.Context, parentName string, shellSessionName string) error {
	ret := _mock.Called(ctx, parentName, shellSessionName)

	if len(ret) == 0 {
		panic("no return value specified for LinkShellSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, parentName, shellSessionName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionWriter_LinkShellSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkShellSession'
type MockSessionWriter_LinkShellSession_Call struct {
	*mock.Call
}

// LinkShellSession is a helper method to define mock.On call
//   - ctx context.Context
//   - parentName string
//   - shellSessionName string
func (_e *MockSessionWriter_Expecter) LinkShellSession(ctx interface{}, parentName interface{}, shellSessionName interface{}) *MockSessionWriter_LinkShellSession_Call {
	return &MockSessionWriter_LinkShellSession_Call{Call: _e.mock.On("LinkShellSession", ctx, parentName, shellSessionName)}
}

func (_c *MockSessionWriter_LinkShellSession_Call) Run(run func(ctx context.Context, parentName string, shellSessionName string)) *MockSessionWriter_LinkShellSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionWriter_LinkShellSession_Call) Return(err error) *MockSessionWriter_LinkShellSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionWriter_LinkShellSession_Call) RunAndReturn(run func(ctx context.Context, parentName string, shellSessionName string) error) *MockSessionWriter_LinkShellSession_Call {
	_c.Call.Return(run)
	return _c
}

// SwapPositions provides a mock function for the type MockSessionWriter
func (_mock *MockSessionWriter) SwapPositions(ctx context.Context, name1 string, name2 string) error {
	ret := _mock.Called(ctx, name1, name2)

	if len(ret) == 0 {
		panic("no return value specified for SwapPositions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name1, name2)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionWriter_SwapPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwapPositions'
type MockSessionWriter_SwapPositions_Call struct {
	*mock.Call
}

// SwapPositions is a helper method to define mock.On call
//   - ctx context.Context
//   - name1 string
//   - name2 string
func (_e *MockSessionWriter_Expecter) SwapPositions(ctx interface{}, name1 interface{}, name2 interface{}) *MockSessionWriter_SwapPositions_Call {
	return &MockSessionWriter_SwapPositions_Call{Call: _e.mock.On("SwapPositions", ctx, name1, name2)}
}

func (_c *MockSessionWriter_SwapPositions_Call) Run(run func(ctx context.Context, name1 string, name2 string)) *MockSessionWriter_SwapPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionWriter_SwapPositions_Call) Return(err error) *MockSessionWriter_SwapPositions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionWriter_SwapPositions_Call) RunAndReturn(run func(ctx context.Context, name1 string, name2 string) error) *MockSessionWriter_SwapPositions_Call {
	_c.Call.Return(run)
	return _c
}
