// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/renato0307/rocha/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Add(ctx context.Context, session domain.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockSessionRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - session domain.Session
func (_e *MockSessionRepository_Expecter) Add(ctx interface{}, session interface{}) *MockSessionRepository_Add_Call {
	return &MockSessionRepository_Add_Call{Call: _e.mock.On("Add", ctx, session)}
}

func (_c *MockSessionRepository_Add_Call) Run(run func(ctx context.Context, session domain.Session)) *MockSessionRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Session
		if args[1] != nil {
			arg1 = args[1].(domain.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Add_Call) Return(err error) *MockSessionRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Add_Call) RunAndReturn(run func(ctx context.Context, session domain.Session) error) *MockSessionRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSessionRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSessionRepository_Expecter) Close() *MockSessionRepository_Close_Call {
	return &MockSessionRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSessionRepository_Close_Call) Run(run func()) *MockSessionRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionRepository_Close_Call) Return(err error) *MockSessionRepository_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Close_Call) RunAndReturn(run func() error) *MockSessionRepository_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Delete(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSessionRepository_Expecter) Delete(ctx interface{}, name interface{}) *MockSessionRepository_Delete_Call {
	return &MockSessionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockSessionRepository_Delete_Call) Run(run func(ctx context.Context, name string)) *MockSessionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Delete_Call) Return(err error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Get(ctx context.Context, name string) (*domain.Session, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Session, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Session); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSessionRepository_Expecter) Get(ctx interface{}, name interface{}) *MockSessionRepository_Get_Call {
	return &MockSessionRepository_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockSessionRepository_Get_Call) Run(run func(ctx context.Context, name string)) *MockSessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Get_Call) Return(session *domain.Session, err error) *MockSessionRepository_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (*domain.Session, error)) *MockSessionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// LinkShellSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) LinkShellSession(ctx context.Context, parentName string, shellSessionName string) error {
	ret := _mock.Called(ctx, parentName, shellSessionName)

	if len(ret) == 0 {
		panic("no return value specified for LinkShellSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, parentName, shellSessionName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_LinkShellSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkShellSession'
type MockSessionRepository_LinkShellSession_Call struct {
	*mock.Call
}

// LinkShellSession is a helper method to define mock.On call
//   - ctx context.Context
//   - parentName string
//   - shellSessionName string
func (_e *MockSessionRepository_Expecter) LinkShellSession(ctx interface{}, parentName interface{}, shellSessionName interface{}) *MockSessionRepository_LinkShellSession_Call {
	return &MockSessionRepository_LinkShellSession_Call{Call: _e.mock.On("LinkShellSession", ctx, parentName, shellSessionName)}
}

func (_c *MockSessionRepository_LinkShellSession_Call) Run(run func(ctx context.Context, parentName string, shellSessionName string)) *MockSessionRepository_LinkShellSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_LinkShellSession_Call) Return(err error) *MockSessionRepository_LinkShellSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_LinkShellSession_Call) RunAndReturn(run func(ctx context.Context, parentName string, shellSessionName string) error) *MockSessionRepository_LinkShellSession_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) List(ctx context.Context, includeArchived bool) ([]domain.Session, error) {
	ret := _mock.Called(ctx, includeArchived)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) ([]domain.Session, error)); ok {
		return returnFunc(ctx, includeArchived)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) []domain.Session); ok {
		r0 = returnFunc(ctx, includeArchived)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, includeArchived)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSessionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - includeArchived bool
func (_e *MockSessionRepository_Expecter) List(ctx interface{}, includeArchived interface{}) *MockSessionRepository_List_Call {
	return &MockSessionRepository_List_Call{Call: _e.mock.On("List", ctx, includeArchived)}
}

func (_c *MockSessionRepository_List_Call) Run(run func(ctx context.Context, includeArchived bool)) *MockSessionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_List_Call) Return(sessions []domain.Session, err error) *MockSessionRepository_List_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *MockSessionRepository_List_Call) RunAndReturn(run func(ctx context.Context, includeArchived bool) ([]domain.Session, error)) *MockSessionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// LoadState provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) LoadState(ctx context.Context, includeArchived bool) (*domain.SessionCollection, error) {
	ret := _mock.Called(ctx, includeArchived)

	if len(ret) == 0 {
		panic("no return value specified for LoadState")
	}

	var r0 *domain.SessionCollection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) (*domain.SessionCollection, error)); ok {
		return returnFunc(ctx, includeArchived)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) *domain.SessionCollection); ok {
		r0 = returnFunc(ctx, includeArchived)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SessionCollection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, includeArchived)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_LoadState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadState'
type MockSessionRepository_LoadState_Call struct {
	*mock.Call
}

// LoadState is a helper method to define mock.On call
//   - ctx context.Context
//   - includeArchived bool
func (_e *MockSessionRepository_Expecter) LoadState(ctx interface{}, includeArchived interface{}) *MockSessionRepository_LoadState_Call {
	return &MockSessionRepository_LoadState_Call{Call: _e.mock.On("LoadState", ctx, includeArchived)}
}

func (_c *MockSessionRepository_LoadState_Call) Run(run func(ctx context.Context, includeArchived bool)) *MockSessionRepository_LoadState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_LoadState_Call) Return(sessionCollection *domain.SessionCollection, err error) *MockSessionRepository_LoadState_Call {
	_c.Call.Return(sessionCollection, err)
	return _c
}

func (_c *MockSessionRepository_LoadState_Call) RunAndReturn(run func(ctx context.Context, includeArchived bool) (*domain.SessionCollection, error)) *MockSessionRepository_LoadState_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Rename(ctx context.Context, oldName string, newName string, newDisplayName string) error {
	ret := _mock.Called(ctx, oldName, newName, newDisplayName)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, oldName, newName, newDisplayName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockSessionRepository_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - ctx context.Context
//   - oldName string
//   - newName string
//   - newDisplayName string
func (_e *MockSessionRepository_Expecter) Rename(ctx interface{}, oldName interface{}, newName interface{}, newDisplayName interface{}) *MockSessionRepository_Rename_Call {
	return &MockSessionRepository_Rename_Call{Call: _e.mock.On("Rename", ctx, oldName, newName, newDisplayName)}
}

func (_c *MockSessionRepository_Rename_Call) Run(run func(ctx context.Context, oldName string, newName string, newDisplayName string)) *MockSessionRepository_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Rename_Call) Return(err error) *MockSessionRepository_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Rename_Call) RunAndReturn(run func(ctx context.Context, oldName string, newName string, newDisplayName string) error) *MockSessionRepository_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// SaveState provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) SaveState(ctx context.Context, state *domain.SessionCollection) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for SaveState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.SessionCollection) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_SaveState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveState'
type MockSessionRepository_SaveState_Call struct {
	*mock.Call
}

// SaveState is a helper method to define mock.On call
//   - ctx context.Context
//   - state *domain.SessionCollection
func (_e *MockSessionRepository_Expecter) SaveState(ctx interface{}, state interface{}) *MockSessionRepository_SaveState_Call {
	return &MockSessionRepository_SaveState_Call{Call: _e.mock.On("SaveState", ctx, state)}
}

func (_c *MockSessionRepository_SaveState_Call) Run(run func(ctx context.Context, state *domain.SessionCollection)) *MockSessionRepository_SaveState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.SessionCollection
		if args[1] != nil {
			arg1 = args[1].(*domain.SessionCollection)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_SaveState_Call) Return(err error) *MockSessionRepository_SaveState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_SaveState_Call) RunAndReturn(run func(ctx context.Context, state *domain.SessionCollection) error) *MockSessionRepository_SaveState_Call {
	_c.Call.Return(run)
	return _c
}

// SwapPositions provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) SwapPositions(ctx context.Context, name1 string, name2 string) error {
	ret := _mock.Called(ctx, name1, name2)

	if len(ret) == 0 {
		panic("no return value specified for SwapPositions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name1, name2)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_SwapPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwapPositions'
type MockSessionRepository_SwapPositions_Call struct {
	*mock.Call
}

// SwapPositions is a helper method to define mock.On call
//   - ctx context.Context
//   - name1 string
//   - name2 string
func (_e *MockSessionRepository_Expecter) SwapPositions(ctx interface{}, name1 interface{}, name2 interface{}) *MockSessionRepository_SwapPositions_Call {
	return &MockSessionRepository_SwapPositions_Call{Call: _e.mock.On("SwapPositions", ctx, name1, name2)}
}

func (_c *MockSessionRepository_SwapPositions_Call) Run(run func(ctx context.Context, name1 string, name2 string)) *MockSessionRepository_SwapPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_SwapPositions_Call) Return(err error) *MockSessionRepository_SwapPositions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_SwapPositions_Call) RunAndReturn(run func(ctx context.Context, name1 string, name2 string) error) *MockSessionRepository_SwapPositions_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleArchive provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) ToggleArchive(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ToggleArchive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_ToggleArchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleArchive'
type MockSessionRepository_ToggleArchive_Call struct {
	*mock.Call
}

// ToggleArchive is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSessionRepository_Expecter) ToggleArchive(ctx interface{}, name interface{}) *MockSessionRepository_ToggleArchive_Call {
	return &MockSessionRepository_ToggleArchive_Call{Call: _e.mock.On("ToggleArchive", ctx, name)}
}

func (_c *MockSessionRepository_ToggleArchive_Call) Run(run func(ctx context.Context, name string)) *MockSessionRepository_ToggleArchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_ToggleArchive_Call) Return(err error) *MockSessionRepository_ToggleArchive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_ToggleArchive_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockSessionRepository_ToggleArchive_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleFlag provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) ToggleFlag(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ToggleFlag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_ToggleFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleFlag'
type MockSessionRepository_ToggleFlag_Call struct {
	*mock.Call
}

// ToggleFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSessionRepository_Expecter) ToggleFlag(ctx interface{}, name interface{}) *MockSessionRepository_ToggleFlag_Call {
	return &MockSessionRepository_ToggleFlag_Call{Call: _e.mock.On("ToggleFlag", ctx, name)}
}

func (_c *MockSessionRepository_ToggleFlag_Call) Run(run func(ctx context.Context, name string)) *MockSessionRepository_ToggleFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_ToggleFlag_Call) Return(err error) *MockSessionRepository_ToggleFlag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_ToggleFlag_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockSessionRepository_ToggleFlag_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClaudeDir provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateClaudeDir(ctx context.Context, name string, claudeDir string) error {
	ret := _mock.Called(ctx, name, claudeDir)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClaudeDir")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name, claudeDir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateClaudeDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClaudeDir'
type MockSessionRepository_UpdateClaudeDir_Call struct {
	*mock.Call
}

// UpdateClaudeDir is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - claudeDir string
func (_e *MockSessionRepository_Expecter) UpdateClaudeDir(ctx interface{}, name interface{}, claudeDir interface{}) *MockSessionRepository_UpdateClaudeDir_Call {
	return &MockSessionRepository_UpdateClaudeDir_Call{Call: _e.mock.On("UpdateClaudeDir", ctx, name, claudeDir)}
}

func (_c *MockSessionRepository_UpdateClaudeDir_Call) Run(run func(ctx context.Context, name string, claudeDir string)) *MockSessionRepository_UpdateClaudeDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateClaudeDir_Call) Return(err error) *MockSessionRepository_UpdateClaudeDir_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateClaudeDir_Call) RunAndReturn(run func(ctx context.Context, name string, claudeDir string) error) *MockSessionRepository_UpdateClaudeDir_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComment provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateComment(ctx context.Context, name string, comment string) error {
	ret := _mock.Called(ctx, name, comment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name, comment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComment'
type MockSessionRepository_UpdateComment_Call struct {
	*mock.Call
}

// UpdateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - comment string
func (_e *MockSessionRepository_Expecter) UpdateComment(ctx interface{}, name interface{}, comment interface{}) *MockSessionRepository_UpdateComment_Call {
	return &MockSessionRepository_UpdateComment_Call{Call: _e.mock.On("UpdateComment", ctx, name, comment)}
}

func (_c *MockSessionRepository_UpdateComment_Call) Run(run func(ctx context.Context, name string, comment string)) *MockSessionRepository_UpdateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateComment_Call) Return(err error) *MockSessionRepository_UpdateComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateComment_Call) RunAndReturn(run func(ctx context.Context, name string, comment string) error) *MockSessionRepository_UpdateComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDisplayName provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateDisplayName(ctx context.Context, name string, displayName string) error {
	ret := _mock.Called(ctx, name, displayName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDisplayName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name, displayName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateDisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDisplayName'
type MockSessionRepository_UpdateDisplayName_Call struct {
	*mock.Call
}

// UpdateDisplayName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - displayName string
func (_e *MockSessionRepository_Expecter) UpdateDisplayName(ctx interface{}, name interface{}, displayName interface{}) *MockSessionRepository_UpdateDisplayName_Call {
	return &MockSessionRepository_UpdateDisplayName_Call{Call: _e.mock.On("UpdateDisplayName", ctx, name, displayName)}
}

func (_c *MockSessionRepository_UpdateDisplayName_Call) Run(run func(ctx context.Context, name string, displayName string)) *MockSessionRepository_UpdateDisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateDisplayName_Call) Return(err error) *MockSessionRepository_UpdateDisplayName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateDisplayName_Call) RunAndReturn(run func(ctx context.Context, name string, displayName string) error) *MockSessionRepository_UpdateDisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExecutionID provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateExecutionID(ctx context.Context, name string, executionID string) error {
	ret := _mock.Called(ctx, name, executionID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExecutionID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name, executionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateExecutionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExecutionID'
type MockSessionRepository_UpdateExecutionID_Call struct {
	*mock.Call
}

// UpdateExecutionID is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - executionID string
func (_e *MockSessionRepository_Expecter) UpdateExecutionID(ctx interface{}, name interface{}, executionID interface{}) *MockSessionRepository_UpdateExecutionID_Call {
	return &MockSessionRepository_UpdateExecutionID_Call{Call: _e.mock.On("UpdateExecutionID", ctx, name, executionID)}
}

func (_c *MockSessionRepository_UpdateExecutionID_Call) Run(run func(ctx context.Context, name string, executionID string)) *MockSessionRepository_UpdateExecutionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateExecutionID_Call) Return(err error) *MockSessionRepository_UpdateExecutionID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateExecutionID_Call) RunAndReturn(run func(ctx context.Context, name string, executionID string) error) *MockSessionRepository_UpdateExecutionID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePRInfo provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdatePRInfo(ctx context.Context, name string, prInfo *domain.PRInfo) error {
	ret := _mock.Called(ctx, name, prInfo)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePRInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.PRInfo) error); ok {
		r0 = returnFunc(ctx, name, prInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdatePRInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePRInfo'
type MockSessionRepository_UpdatePRInfo_Call struct {
	*mock.Call
}

// UpdatePRInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - prInfo *domain.PRInfo
func (_e *MockSessionRepository_Expecter) UpdatePRInfo(ctx interface{}, name interface{}, prInfo interface{}) *MockSessionRepository_UpdatePRInfo_Call {
	return &MockSessionRepository_UpdatePRInfo_Call{Call: _e.mock.On("UpdatePRInfo", ctx, name, prInfo)}
}

func (_c *MockSessionRepository_UpdatePRInfo_Call) Run(run func(ctx context.Context, name string, prInfo *domain.PRInfo)) *MockSessionRepository_UpdatePRInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *domain.PRInfo
		if args[2] != nil {
			arg2 = args[2].(*domain.PRInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdatePRInfo_Call) Return(err error) *MockSessionRepository_UpdatePRInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdatePRInfo_Call) RunAndReturn(run func(ctx context.Context, name string, prInfo *domain.PRInfo) error) *MockSessionRepository_UpdatePRInfo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRepoSource provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateRepoSource(ctx context.Context, name string, repoSource string) error {
	ret := _mock.Called(ctx, name, repoSource)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRepoSource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name, repoSource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateRepoSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRepoSource'
type MockSessionRepository_UpdateRepoSource_Call struct {
	*mock.Call
}

// UpdateRepoSource is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - repoSource string
func (_e *MockSessionRepository_Expecter) UpdateRepoSource(ctx interface{}, name interface{}, repoSource interface{}) *MockSessionRepository_UpdateRepoSource_Call {
	return &MockSessionRepository_UpdateRepoSource_Call{Call: _e.mock.On("UpdateRepoSource", ctx, name, repoSource)}
}

func (_c *MockSessionRepository_UpdateRepoSource_Call) Run(run func(ctx context.Context, name string, repoSource string)) *MockSessionRepository_UpdateRepoSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateRepoSource_Call) Return(err error) *MockSessionRepository_UpdateRepoSource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateRepoSource_Call) RunAndReturn(run func(ctx context.Context, name string, repoSource string) error) *MockSessionRepository_UpdateRepoSource_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSkipPermissions provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateSkipPermissions(ctx context.Context, name string, skip bool) error {
	ret := _mock.Called(ctx, name, skip)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSkipPermissions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, name, skip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateSkipPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSkipPermissions'
type MockSessionRepository_UpdateSkipPermissions_Call struct {
	*mock.Call
}

// UpdateSkipPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - skip bool
func (_e *MockSessionRepository_Expecter) UpdateSkipPermissions(ctx interface{}, name interface{}, skip interface{}) *MockSessionRepository_UpdateSkipPermissions_Call {
	return &MockSessionRepository_UpdateSkipPermissions_Call{Call: _e.mock.On("UpdateSkipPermissions", ctx, name, skip)}
}

func (_c *MockSessionRepository_UpdateSkipPermissions_Call) Run(run func(ctx context.Context, name string, skip bool)) *MockSessionRepository_UpdateSkipPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateSkipPermissions_Call) Return(err error) *MockSessionRepository_UpdateSkipPermissions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateSkipPermissions_Call) RunAndReturn(run func(ctx context.Context, name string, skip bool) error) *MockSessionRepository_UpdateSkipPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateState provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateState(ctx context.Context, name string, state domain.SessionState, executionID string) error {
	ret := _mock.Called(ctx, name, state, executionID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.SessionState, string) error); ok {
		r0 = returnFunc(ctx, name, state, executionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateState'
type MockSessionRepository_UpdateState_Call struct {
	*mock.Call
}

// UpdateState is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - state domain.SessionState
//   - executionID string
func (_e *MockSessionRepository_Expecter) UpdateState(ctx interface{}, name interface{}, state interface{}, executionID interface{}) *MockSessionRepository_UpdateState_Call {
	return &MockSessionRepository_UpdateState_Call{Call: _e.mock.On("UpdateState", ctx, name, state, executionID)}
}

func (_c *MockSessionRepository_UpdateState_Call) Run(run func(ctx context.Context, name string, state domain.SessionState, executionID string)) *MockSessionRepository_UpdateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.SessionState
		if args[2] != nil {
			arg2 = args[2].(domain.SessionState)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateState_Call) Return(err error) *MockSessionRepository_UpdateState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateState_Call) RunAndReturn(run func(ctx context.Context, name string, state domain.SessionState, executionID string) error) *MockSessionRepository_UpdateState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateStatus(ctx context.Context, name string, status *string) error {
	ret := _mock.Called(ctx, name, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) error); ok {
		r0 = returnFunc(ctx, name, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockSessionRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - status *string
func (_e *MockSessionRepository_Expecter) UpdateStatus(ctx interface{}, name interface{}, status interface{}) *MockSessionRepository_UpdateStatus_Call {
	return &MockSessionRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, name, status)}
}

func (_c *MockSessionRepository_UpdateStatus_Call) Run(run func(ctx context.Context, name string, status *string)) *MockSessionRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateStatus_Call) Return(err error) *MockSessionRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, name string, status *string) error) *MockSessionRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
