// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSoundPlayer creates a new instance of MockSoundPlayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSoundPlayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSoundPlayer {
	mock := &MockSoundPlayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSoundPlayer is an autogenerated mock type for the SoundPlayer type
type MockSoundPlayer struct {
	mock.Mock
}

type MockSoundPlayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSoundPlayer) EXPECT() *MockSoundPlayer_Expecter {
	return &MockSoundPlayer_Expecter{mock: &_m.Mock}
}

// PlaySound provides a mock function for the type MockSoundPlayer
func (_mock *MockSoundPlayer) PlaySound() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PlaySound")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSoundPlayer_PlaySound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaySound'
type MockSoundPlayer_PlaySound_Call struct {
	*mock.Call
}

// PlaySound is a helper method to define mock.On call
func (_e *MockSoundPlayer_Expecter) PlaySound() *MockSoundPlayer_PlaySound_Call {
	return &MockSoundPlayer_PlaySound_Call{Call: _e.mock.On("PlaySound")}
}

func (_c *MockSoundPlayer_PlaySound_Call) Run(run func()) *MockSoundPlayer_PlaySound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSoundPlayer_PlaySound_Call) Return(err error) *MockSoundPlayer_PlaySound_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSoundPlayer_PlaySound_Call) RunAndReturn(run func() error) *MockSoundPlayer_PlaySound_Call {
	_c.Call.Return(run)
	return _c
}

// PlaySoundForEvent provides a mock function for the type MockSoundPlayer
func (_mock *MockSoundPlayer) PlaySoundForEvent(eventType string) error {
	ret := _mock.Called(eventType)

	if len(ret) == 0 {
		panic("no return value specified for PlaySoundForEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(eventType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSoundPlayer_PlaySoundForEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaySoundForEvent'
type MockSoundPlayer_PlaySoundForEvent_Call struct {
	*mock.Call
}

// PlaySoundForEvent is a helper method to define mock.On call
//   - eventType string
func (_e *MockSoundPlayer_Expecter) PlaySoundForEvent(eventType interface{}) *MockSoundPlayer_PlaySoundForEvent_Call {
	return &MockSoundPlayer_PlaySoundForEvent_Call{Call: _e.mock.On("PlaySoundForEvent", eventType)}
}

func (_c *MockSoundPlayer_PlaySoundForEvent_Call) Run(run func(eventType string)) *MockSoundPlayer_PlaySoundForEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSoundPlayer_PlaySoundForEvent_Call) Return(err error) *MockSoundPlayer_PlaySoundForEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSoundPlayer_PlaySoundForEvent_Call) RunAndReturn(run func(eventType string) error) *MockSoundPlayer_PlaySoundForEvent_Call {
	_c.Call.Return(run)
	return _c
}
