// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClaudeDirResolver creates a new instance of MockClaudeDirResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClaudeDirResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClaudeDirResolver {
	mock := &MockClaudeDirResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClaudeDirResolver is an autogenerated mock type for the ClaudeDirResolver type
type MockClaudeDirResolver struct {
	mock.Mock
}

type MockClaudeDirResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClaudeDirResolver) EXPECT() *MockClaudeDirResolver_Expecter {
	return &MockClaudeDirResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockClaudeDirResolver
func (_mock *MockClaudeDirResolver) Resolve(repoInfo string, userOverride string) string {
	ret := _mock.Called(repoInfo, userOverride)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(repoInfo, userOverride)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClaudeDirResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockClaudeDirResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - repoInfo string
//   - userOverride string
func (_e *MockClaudeDirResolver_Expecter) Resolve(repoInfo interface{}, userOverride interface{}) *MockClaudeDirResolver_Resolve_Call {
	return &MockClaudeDirResolver_Resolve_Call{Call: _e.mock.On("Resolve", repoInfo, userOverride)}
}

func (_c *MockClaudeDirResolver_Resolve_Call) Run(run func(repoInfo string, userOverride string)) *MockClaudeDirResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClaudeDirResolver_Resolve_Call) Return(s string) *MockClaudeDirResolver_Resolve_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClaudeDirResolver_Resolve_Call) RunAndReturn(run func(repoInfo string, userOverride string) string) *MockClaudeDirResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
